//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

#ifndef SUPPORT_INTERPRETER_BYTECODEINTERPRETER_H
#define SUPPORT_INTERPRETER_BYTECODEINTERPRETER_H

#include "Mojo/Interpreter/InterpreterState.h"
#include "mlir/IR/OpDefinition.h"

namespace M {

//===----------------------------------------------------------------------===//
// FunctionIRBytecode
//===----------------------------------------------------------------------===//

/// This class represents interpreter bytecode for a function region as a blob.
class FunctionIRBytecode {
public:
  /// Free the blob and clean up other metadata on destruction.
  ~FunctionIRBytecode();

  /// Move constructor.
  FunctionIRBytecode(FunctionIRBytecode &&other)
      : numValues(other.numValues), data(other.data),
        cfgIndices(std::move(other.cfgIndices)) {
    other.data = nullptr;
  }

  /// Generate interpreter bytecode for the given function region.
  static ErrorTreeOr<FunctionIRBytecode> compile(Region &entry,
                                                 TargetInfoAttr target);

private:
  FunctionIRBytecode(unsigned numValues, void *data,
                     DenseMap<const void *, uint32_t> &&cfgIndices)
      : numValues(numValues), data(data), cfgIndices(std::move(cfgIndices)) {}

  /// Read a value at the given offset. This is used by the bytecode
  /// interpreter.
  template <typename T>
  const T *at(uint32_t offset) const {
    return (const T *)((uint8_t *)data + offset);
  }

  /// This is the number of SSA values "allocated" for the function. This is
  /// used to quickly resize the vector in the stack frame that holds the
  /// interpreter ADTs.
  unsigned numValues;
  /// The is the pointer to the bytecode blob.
  void *data;
  /// Because MLIR doesn't have a representation for region control flow, we
  /// have to manually map regions and operations to bytecode offsets.
  DenseMap<const void *, uint32_t> cfgIndices;

  /// Allow the interpreter to read the internals.
  friend class BytecodeInterpreter;
};

//===----------------------------------------------------------------------===//
// BytecodeInterpreter
//===----------------------------------------------------------------------===//

/// This is a required interface by the bytecode interpreter. The bytecode
/// compiler takes a region and generates the interpreter bytecode for it and
/// manages the lifetimes of the bytecodes.
///
/// It can, for example, implement pre-processing and caching policies.
class BytecodeCompiler {
public:
  virtual ~BytecodeCompiler() = default;
  virtual ErrorTreeOr<const FunctionIRBytecode *>
  compileBytecode(Region &region) = 0;
};

/// The bytecode interpreter is an implementation of the interpreter execution
/// model that operates over a generated bytecode representation that amortizes
/// the costs of directly interpreting the IR.
class BytecodeInterpreter : public InterpreterState {
public:
  /// Initialize the interpreter with a target and a bytecode compiler instance.
  BytecodeInterpreter(TargetInfoAttr target, BytecodeCompiler *bcCompiler)
      : InterpreterState(target), bcCompiler(bcCompiler),
        // Aggressively reserve memory to reduce memory pressure.
        operands(/*initialSize=*/32) {
    stack.reserve(256);
    results.reserve(32);
  }

  // Required interpreter public interface.
  ErrorTreeOrSuccess callFunctionBody(Region &body,
                                      ArrayRef<Attribute> arguments) override;
  ErrorTreeOrSuccess
  returnFromFunction(ArrayRef<Attribute> returnValues) override;
  ErrorTreeOrSuccess transferControlFlowTo(Operation *target,
                                           ArrayRef<Attribute> values) override;
  ErrorTreeOrSuccess
  transferControlFlowTo(Region &target, ArrayRef<Attribute> arguments) override;
  ErrorTreeOrSuccess mapResults(ArrayRef<Attribute> results) override;

  /// Interpret a generic operation by trying to use its operation folder.
  ErrorTreeOrSuccess
  interpretOpWithFolder(Operation *op, ArrayRef<Attribute> operands) override;

private:
  struct StackFrame {
    Operation *func;
    size_t numStackAllocs;
    size_t numSymbolicAllocs;

    /// This is the bytecode offset of the calling operation, to which the
    /// function should branch back when it returns.
    uint32_t origin;
    /// This is a pointer to the bytecode for the calling function. If it is
    /// null, then this is the entry function frame.
    const FunctionIRBytecode *originBc;
    /// These are the slots for SSA values for the scope of this function.
    ReallocatingTrivialVector<Attribute> values;
  };

  // Required interpreter private interface.
  ErrorTree addStackTrace(ErrorTree err) override;
  Operation *getOrigin(size_t depth) override;
  void resetExecutor() override;
  void notifyAllocationOnFrame() override;
  ErrorTreeOr<SmallVector<Attribute>>
  interpretFunction(Region &body, ArrayRef<Attribute> arguments) override;

  StackFrame &getCurrentFrame() { return stack.back(); }

  /// The bytecode compiler instance to use.
  BytecodeCompiler *bcCompiler;

  /// These are the stack frames kept by the interpreter.
  SoftPopStack<StackFrame> stack;

  /// The operation current offset into the function bytecode.
  uint32_t pc = -1;
  /// This is the bytecode of the current active function, placed here for
  /// faster access.
  const FunctionIRBytecode *bc = nullptr;
  /// These are the current values to use in the function.
  Attribute *values = nullptr;
  /// This is set to true if an operation transferred control flow.
  bool didTransfer = false;

  /// Operands to feed into operations.
  ReallocatingTrivialVector<Attribute> operands;
  /// Operation fold results.
  SmallVector<OpFoldResult> results;

  /// The values to use when exiting the interpreter.
  ArrayRef<Attribute> exitValues;
};

} // namespace M

#endif // SUPPORT_INTERPRETER_BYTECODEINTERPRETER_H
