load("//bazel:api.bzl", "modular_py_library")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "dflash2_qwen3_5",
    srcs = glob(["**/*.py"]),
    deps = [
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/llama3",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/kv_cache",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
    ],
)
