# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
from enum import Enum
from typing import Generic, Literal, TypeVar

import msgspec
from max.pipelines.context import TextContext
from max.pipelines.kv_cache import TransferReqData
from max.pipelines.modeling.types import RequestID

ContextType = TypeVar("ContextType", bound=TextContext)


class SchedulerProgress(Enum):
    """Indicates whether a scheduler made progress during an iteration."""

    MADE_PROGRESS = "made_progress"
    NO_PROGRESS = "no_progress"


class PrefillRequest(
    msgspec.Struct,
    Generic[ContextType],
    tag=True,
    omit_defaults=True,
    kw_only=True,
):
    """A request for prefill (context encoding) processing.

    Contains the request ID, input context, and transfer engine details needed to
    process a prefill request through the pipeline and transfer KV cache data.

    Generic over the context type: msgspec decodes each field at its declared
    type, so the DI prefill decoder must be parameterized with the
    architecture's concrete context subclass (e.g. a ``TextAndVisionContext``
    subclass for VLMs) or the wire silently narrows the context to the base
    class, dropping vision fields. The ``tag`` stays the class name
    (``"PrefillRequest"``) for every parameterization, keeping the decode
    client and prefill server wire-compatible.
    """

    id: RequestID
    """Unique identifier for this request."""
    context: ContextType
    """The input context containing the request data and state."""
    transfer_engine_name: str
    """Name of the transfer engine to use for KV cache transfers."""
    dst_block_ids: list[int]
    """List of block IDs allocated for KV cache storage on Decode."""
    dst_replica_idx: int
    """The replica the request is on Decode."""


class PrefillResponse(
    msgspec.Struct, tag=True, omit_defaults=True, kw_only=True
):
    """A response for prefill (context encoding) processing.

    Contains the request ID and input context needed to run decode
    and generate tokens based on the prefill finished.
    """

    id: RequestID
    """Unique identifier for this request."""
    generated_token_id: int
    """The first generated token from prefill."""
    transfer_metadata: TransferReqData
    """The transfer metadata for the KV cache transfers."""
    draft_tokens: list[int] | None = None
    """Draft tokens generated by the Eagle/MTP draft model during prefill. When present, the decode node can feed these into its first speculative-decode iteration instead of starting with an empty draft cache."""


class PrefillProgressPing(
    msgspec.Struct, tag=True, omit_defaults=True, kw_only=True
):
    """A prefill-side progress event, relayed to decode for latency
    instrumentation.

    Carries no timing data itself: decode timestamps *receipt* on its own
    clock, against the send time it recorded for the originating request.
    This keeps every derived interval a same-clock diff, since a raw
    timestamp from prefill's clock is not comparable to decode's.
    """

    id: RequestID
    """Unique identifier of the request this ping is about."""
    event: Literal["arrived", "ce_done"]
    """Which milestone this ping reports: request received and enqueued at
    prefill, or the request's CE batch finished executing."""


class PrefillFailure(
    msgspec.Struct, tag=True, omit_defaults=True, kw_only=True
):
    """A prefill request the prefill node rejected without running it.

    Lets the decode node terminate the request with the reason instead of
    waiting out its TTL for a ``PrefillResponse`` that never arrives.
    """

    id: RequestID
    """Unique identifier of the failed request."""
    error: str
    """User-facing description of why the request failed."""


class CancelRequest(msgspec.Struct, tag=True, omit_defaults=True, kw_only=True):
    """A request to cancel an ongoing request.

    Used to signal that a specific request should be cancelled and its resources
    should be freed. This is typically used to cancel prefill or decode requests
    that are no longer needed.
    """

    id: RequestID
    """Unique identifier of the request to cancel."""
