load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "scheduler",
    srcs = glob(["**/*.py"]),
    deps = [
        "//max/python/max/driver",
        "//max/python/max/nn",
        "//max/python/max/pipelines/audio",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/diffusion",
        "//max/python/max/pipelines/kv_cache",
        "//max/python/max/pipelines/kv_cache:kv_connector",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/lora",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/pipelines/speculative",
        "//max/python/max/profiler",
        "//max/python/max/serve:config",
        "//max/python/max/serve:queue",
        "//max/python/max/serve:scheduler_result",
        "//max/python/max/serve/telemetry",
        "//max/python/max/serve/worker_interface",
        "//max/python/max/support",
        requirement("msgspec"),
        requirement("opentelemetry-api"),
    ],
)
