//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

#include "Mojo/MojoParser/EntryPoint.h"
#include "Mojo/MojoParser/ASTDecl.h"
#include "Mojo/MojoParser/DeclResolver.h"
#include "Mojo/MojoParser/SharedState.h"

#include "AsyncRT/Runtime/CPUDevice.h"
#include "Mojo/KGENDialect/KGENOps.h"
#include "Mojo/LITDialect/LITOps.h"
#include "Mojo/Support/CompilerProfiling.h"
#include "Mojo/Support/MojoPrecompiledFile.h"
#include "Mojo/ToolCommon/CompilationOptions.h"
#include "Support/Compiler/BytecodeReaderWriter.h"
#include "Support/Filesystem/Paths.h"
#include "Support/Telemetry/Telemetry.h"
#include "mlir/Bytecode/Encoding.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Support/Timing.h"
#include "llvm/Support/SourceMgr.h"

using namespace M;
using namespace KGEN;
using namespace LIT;

//===----------------------------------------------------------------------===//
// Diagnostic Utils
//===----------------------------------------------------------------------===//

llvm::SMLoc LIT::findStartOfNextToken(SharedState &shared, StringRef string) {
  Lexer lexer(shared.diags, string, string.data());
  return lexer.getToken().getLoc();
}

//===----------------------------------------------------------------------===//
// Driver Entry Points
//===----------------------------------------------------------------------===//

/// Sort the order of uses of the given value using the given set of operation
/// IDs. This ensures a deterministic order of uses.
static void sortValueUses(Value value,
                          DenseMap<Operation *, unsigned> &operationIDs) {
  if (value.use_empty() || value.hasOneUse())
    return;

  // The current use list order for each of the uses of the value.
  SmallVector<std::pair<unsigned, uint64_t>> currentOrder;

  // Functor to record a new use to the current order.
  auto addUse = [&](unsigned index, OpOperand &operand) {
    uint64_t nextID =
        mlir::bytecode::getUseID(operand, operationIDs.at(operand.getOwner()));
    currentOrder.emplace_back(index, nextID);
    return nextID;
  };

  // Compute the current order of the use-list with respect to the global
  // ordering. Detect if the order is already sorted while doing so.
  uint64_t currentID = addUse(0, *value.use_begin());
  bool isSorted = true;
  for (auto it : llvm::drop_begin(llvm::enumerate(value.getUses()))) {
    uint64_t nextID = addUse(it.index(), it.value());
    isSorted &= std::exchange(currentID, nextID) >= nextID;
  }
  // If we know the list is already sorted, there is nothing left to do.
  if (isSorted)
    return;

  // Sort the order based on the operation user, and build the shuffled order
  // mapping.
  llvm::sort(currentOrder, [](auto elem1, auto elem2) {
    return elem1.second > elem2.second;
  });
  SmallVector<unsigned> shuffledOrder(currentOrder.size());
  for (unsigned i = 0, e = currentOrder.size(); i != e; ++i)
    shuffledOrder[currentOrder[i].first] = i;
  value.shuffleUseList(shuffledOrder);
}

/// Sort the order of uses of values defined within the given top level
/// operation. This enforces a deterministic order to the uses, and ensures that
/// any generated bytecode is stable across compilations (regardless of how the
/// IR was parsed).
static void sortValueUses(Operation *topLevelOp) {
  unsigned operationID = 0;
  DenseMap<Operation *, unsigned> operationIDs;
  topLevelOp->walk([&](Operation *op, mlir::WalkStage stage) {
    // Before visiting any of the regions of the operation, we simply check if
    // we should record this operation's ID (i.e. if it has operands).
    if (stage.isBeforeAllRegions()) {
      if (op->getNumOperands())
        operationIDs.insert({op, operationID++});
      return;
    }

    // After the walk has finished, sort the uses of all values defined within
    // this operation.
    if (stage.isAfterAllRegions()) {
      for (Region &region : op->getRegions()) {
        for (Block &block : region) {
          for (BlockArgument &arg : block.getArguments())
            sortValueUses(arg, operationIDs);
          for (Operation &op : block)
            for (Value result : op.getResults())
              sortValueUses(result, operationIDs);
        }
      }
    }
  });
}

/// Erase all declarations unreachable from the main module. This is primarily
/// useful when there are imported modules that were not lazily loaded from the
/// cache. This function should run after textual modules are saved to the
/// cache, reducing the amount of IR reaching the compiler. In addition, it
/// provides the compiler a canonical form of IR coming out of the parser. This,
/// for instance, ensures the cache key computed on parser output does not
/// depend on whether the parser has cache hits for lazy loading.
static void eraseUnreachableDecls(Operation *declOp, ModuleOp module,
                                  bool preserveClosureTraitMethods = false) {
  CompilerTimeTraceScope traceScope("eraseUnreachableDecls");

  // Precompute a map from structs to their extensions, this will help with
  // marking extensions as live further below.
  DenseMap<SymbolRefAttr, SmallVector<LIT::ExtensionDeclOp>> structToExtensions;

  // Start by erasing unresolved imports. This puts the module in a
  // canonical form.
  module.walk<mlir::WalkOrder::PreOrder>([&](Operation *op) {
    // Populate the structToExtensions map.
    if (auto ext = dyn_cast<LIT::ExtensionDeclOp>(op)) {
      if (auto targetStruct = ext.getTargetStruct())
        structToExtensions[targetStruct.value()].push_back(ext);
    }

    if (op == declOp) {
      // Don't purge anything from the main package if we are parsing one.
      if (isa<PackageOp>(op))
        return WalkResult::skip();
      op->walk<mlir::WalkOrder::PreOrder>([](Operation *op) {
        if (isa<ImportOp, UnresolvedImportOp, UnresolvedWildcardImportOp>(op)) {
          op->erase();
          return WalkResult::skip();
        }
        if (isa<StructDeclOp, FnOp, LIT::TraitDeclOp, LIT::ExtensionDeclOp>(
                op)) {
          op->walk([](Operation *nested) {
            if (isa<ImportOp>(nested))
              nested->erase();
          });
          return WalkResult::skip();
        }
        return WalkResult::advance();
      });
      return WalkResult::skip();
    }

    // Remove all alias decls outside functions and the main decl.
    if (isa<ImportOp, UnresolvedImportOp, UnresolvedWildcardImportOp,
            AliasDeclOp>(op)) {
      op->erase();
      return WalkResult::skip();
    }
    // Functions have nothing to check inside them.
    if (isa<FnOp, TraitDeclOp>(op))
      return WalkResult::skip();
    return WalkResult::advance();
  });

  // The remaining skippable decls are all symbol operations. Run symbol DCE
  // rooted at the main module.
  mlir::SymbolTableCollection symtab;
  DenseSet<Operation *> liveSymbols;
  std::vector<Operation *> worklist;
  declOp->walk([&](Operation *op) {
    if (isa<mlir::SymbolOpInterface>(op)) {
      liveSymbols.insert(op);
      worklist.push_back(op);
    }
  });

  // This walker will mark all referenced symbols as live.
  mlir::AttrTypeWalker refCollector;
  auto markLive = [&](Operation *op) {
    if (liveSymbols.insert(op).second)
      worklist.push_back(op);
  };
  refCollector.addWalk([&](SymbolRefAttr ref) {
    // Mark all referenced symbols as live. Invalid symbol references will get
    // caught by the verifier.
    SmallVector<Operation *, 4> symbols;
    if (failed(symtab.lookupSymbolIn(module, ref, symbols)))
      return;
    for (Operation *symbol : symbols)
      markLive(symbol);
  });

  // Propagate liveness.
  while (!worklist.empty()) {
    Operation *cur = worklist.back();
    worklist.pop_back();

    // Extensions are not children of structs, so they won't be found by walking
    // the struct.
    // For now, let's conservatively say that if a struct is live, all
    // extensions that target it are marked live.
    // TODO(MOCO-522): Factor in uses of the conformance, and uses of the
    // methods perhaps? Could be more precise and avoid the need for a map.
    if (auto structOp = dyn_cast<LIT::StructDeclOp>(cur)) {
      SymbolRefAttr structRef = LIT::getFullyResolvedSymbolRef(structOp);
      auto it = structToExtensions.find(structRef);
      if (it != structToExtensions.end()) {
        for (LIT::ExtensionDeclOp ext : it->second)
          markLive(ext);
      }
    }

    // If preserving closure trait methods, mark all functions in closure traits
    // as live when the trait itself is live.
    if (preserveClosureTraitMethods) {
      if (auto traitOp = dyn_cast<LIT::TraitDeclOp>(cur)) {
        if (traitOp.getClosureSignature().has_value())
          traitOp.walk([&](FnOp fn) { markLive(fn); });
      }
    }

    // Collect symbol references between this symbol table and any child symbol
    // tables. Nested `lit.fn` operations are trickier, however.
    cur->walk<mlir::WalkOrder::PreOrder>([&](Operation *op) {
      if (op != cur) {
        // Mark nested functions as live, which also recurses on them.
        if (auto func = dyn_cast<FnOp>(op); func && func.getParamDeclAttr())
          markLive(func);
        // Witness tables & witness entries are part of the struct type spec, so
        // they need to be live for elaboration time generics.
        if (isa<ConformanceOp, WitnessOp>(op))
          markLive(op);
        if (op->hasTrait<OpTrait::SymbolTable>())
          return WalkResult::skip();
      }
      refCollector.walk(op->getAttrDictionary());
      for (Region &region : op->getRegions()) {
        for (Block &block : region)
          for (Type type : block.getArgumentTypes())
            refCollector.walk(type);
      }
      for (Type type : op->getResultTypes())
        refCollector.walk(type);
      return WalkResult::advance();
    });
  }

  // Walk post-order to erase dead symbols.
  module.walk<mlir::WalkOrder::PreOrder>([&](Operation *op) -> WalkResult {
    // Don't purge anything from the main package if we are parsing one.
    if (op == declOp && isa<PackageOp>(declOp))
      return WalkResult::skip();

    if (isa<mlir::SymbolOpInterface, FnOp>(op) && !liveSymbols.contains(op)) {
      // Never remove the __del__ function from Deinitable or the
      // __moveinit__ function from Movable.  These are used by CheckLifetimes.
      if (auto fnOp = dyn_cast<FnOp>(op);
          // Some REPL tests are not resolving MoveInit at all.
          fnOp && fnOp->getNumRegions() == 1 && !fnOp.getBodyRegion().empty()) {
        auto parentOp = fnOp->getParentOp();
        if (fnOp.getSpecialFunctionKind() == SpecialFunctionKind::kDeinit &&
            isa_and_nonnull<TraitDeclOp>(parentOp) &&
            cast<TraitDeclOp>(parentOp).getSymName() == "Deinitable")
          return WalkResult::skip();
        if (fnOp.getSpecialFunctionKind() == SpecialFunctionKind::kMoveCtor &&
            isa_and_nonnull<TraitDeclOp>(parentOp) &&
            cast<TraitDeclOp>(parentOp).getSymName() == "Movable")
          return WalkResult::skip();
      }

      op->erase();
      return WalkResult::skip();
    }

    // We never need to erase anything inside functions.
    if (isa<FnOp>(op))
      return WalkResult::skip();

    return WalkResult::advance();
  });
}

/// Parse a mojo module or package into the specified MLIR context. Returns the
/// resultant IR, and the decl for the module or package. This abstracts away
/// the shared setup between module and package parsing.
static std::tuple<OwningOpRef<mlir::ModuleOp>, ASTDecl *>
importMojoImpl(ContextRef context, StringRef moduleIdentifier,
               SourceMgr &sourceMgr, SharedState &sharedState,
               mlir::TimingScope &ts,
               SmallVectorImpl<std::string> *includedFiles,
               function_ref<ASTDecl &(ModuleOp)> buildDeclFn) {
  auto fileLoc =
      sharedState.createLocation(moduleIdentifier, /*line=*/1, /*column=*/1);
  llvm::StringMap<Telemetry::MetricAttributeValue> attrs = {
      {"filename", fileLoc.getFilename().str()}};
  [[maybe_unused]] auto timeScope =
      context->get<Telemetry::TelemetryContext>()
          ->createUInt64Timer<std::chrono::milliseconds>(
              "mojo.parser.compile.time", M::Telemetry::Level::L2, attrs);

  // This is the result module we are parsing into.
  mlir::OwningOpRef<ModuleOp> module(ModuleOp::create(fileLoc));

  // Build the decl for the main module.
  ASTDecl &moduleDecl = buildDeclFn(*module);

  // Resolve everything within the main input module.
  sharedState.declResolver->resolveAllReferencedFrom(moduleDecl);

  // Finalize the imported bytecode now that we've resolved everything. This
  // will drop bytecode operations that never got referenced.
  if (failed(sharedState.finalizeImportedBytecodeModules()))
    return {nullptr, nullptr};

  // We fail either if we have a non-recoverable parse error, or if we emitted
  // an error and then recovered.  In either case, the IR will not be valid and
  // the caller should not verify it.
  if (sharedState.diags.isErrorEmitted())
    return {nullptr, nullptr};

#ifndef MODULAR_PRODUCTION
  // Make sure the parse module has no other structural problems detected by
  // the verifier.
  {
    auto verificationTimer = ts.nest("Verify module");
    if (failed(mlir::verify(*module)))
      return {};
  }
#endif // MODULAR_PRODUCTION

  // Closure traits live outside module so we cannot distinguish between those
  // that were defined by this unit and those that were defined by dependencies.
  // The difference between a trait defined by the unit and one defined by the
  // dependency is that the methods of the latter need not persist. The same is
  // not true for the former. Opt to keep all methods of closure traits to
  // guarantee correctness.
  eraseUnreachableDecls(moduleDecl.getIfOperation(), *module,
                        /*preserveClosureTraitMethods=*/true);
  sortValueUses(*module);

  // Set the included files if requested.
  if (includedFiles)
    llvm::append_range(*includedFiles, sharedState.getIncludedFiles());
  return {std::move(module), &moduleDecl};
}

/// Parse the specified Mojo file into the specified MLIR context. Returns the
/// resultant IR, and the decl for the module represented by the input file.
static std::tuple<OwningOpRef<mlir::ModuleOp>, ASTDecl *>
importMojoFileImpl(ContextRef context, SourceMgr &sourceMgr,
                   SharedState &sharedState, mlir::TimingScope &ts,
                   SmallVectorImpl<std::string> *includedFiles) {
  auto sourceBuf = sourceMgr.getMemoryBuffer(sourceMgr.getMainFileID());
  StringRef bufName = sourceBuf->getBufferIdentifier();
  DebugInfo::DIBuilder::ScopeGuard fileGuard;

  return importMojoImpl(
      context, bufName, sourceMgr, sharedState, ts, includedFiles,
      [&](ModuleOp module) -> ASTDecl & {
        Lexer lexer(sharedState.diags, sourceBuf);
        auto startSMLoc = lexer.getToken().getLoc();

        // Create the top-level outer decl, which will contain all things we
        // parse.
        ASTDecl &topLevelDecl = sharedState.declResolver->addDecl(
            module, startSMLoc, StringAttr(), /*parentDecl=*/nullptr,
            lexer.getCursor(), LexerCursor::getEOF(sourceBuf), -1);
        sharedState.initialize(topLevelDecl);

        // If we are emitting debug info, create a file entry for this file.
        if (sharedState.diBuilder)
          fileGuard = sharedState.diBuilder->pushFile(
              sharedState.diags.getCanonicalFilename(bufName));

        // Grab a module name for the current input, choosing a dummy name if we
        // don't have one that's valid.
        std::string moduleName =
            std::filesystem::path(bufName.str()).stem().string();
        if (moduleName.empty())
          moduleName = "<input>";

        // Build the input module.
        return sharedState.createModule(moduleName, sourceBuf,
                                        cast<FileLineColLoc>(module->getLoc()));
      });
}

std::pair<OwningOpRef<ModuleOp>, PackageOp>
LIT::importMojoPackage(ContextRef context, StringRef path,
                       StringRef packageName, llvm::SourceMgr &sourceMgr,
                       ParserConfig &config, mlir::TimingScope &ts,
                       SmallVectorImpl<std::string> *includedFiles) {
  // Emit an error if the path doesn't actually correspond with a package.
  if (!Filesystem::isMojoSourcePackagePath(path.str())) {
    sourceMgr.PrintMessage({}, llvm::SourceMgr::DK_Error,
                           "provided path '" + path +
                               "' does not correspond to a package");
    return {};
  }
  SharedState sharedState(sourceMgr, config);
  DebugInfo::DIBuilder::ScopeGuard fileGuard;

  auto [module, packageDecl] = importMojoImpl(
      context, path, sourceMgr,
      // TODO(MOCO-1295): Generate Python bindings for Mojo packages.
      sharedState, ts, includedFiles, [&](ModuleOp module) -> ASTDecl & {
        // Create the top-level outer decl, which will contain all things we
        // parse.
        ASTDecl &topLevelDecl = sharedState.declResolver->addDecl(
            module, SMLoc(), StringAttr(), /*parentDecl=*/nullptr,
            LexerCursor(), LexerCursor(), /*indentation=*/-1);
        sharedState.initialize(topLevelDecl);

        if (sharedState.diBuilder)
          fileGuard = sharedState.diBuilder->pushFile(path);

        // Build the package.
        return sharedState.createPackage(path, packageName);
      });
  if (!module)
    return {};
  return {std::move(module),
          cast_or_null<PackageOp>(packageDecl->getIfOperation())};
}

OwningOpRef<mlir::ModuleOp>
LIT::importMojoFile(ContextRef context, llvm::SourceMgr &sourceMgr,
                    ParserConfig &config, mlir::TimingScope &ts,
                    SmallVectorImpl<std::string> *includedFiles) {
  SharedState sharedState(sourceMgr, config);
  auto [module, topLevelDecl] =
      importMojoFileImpl(context, sourceMgr, sharedState, ts, includedFiles);
  return std::move(module);
}

OwningOpRef<ModuleOp> LIT::cloneDeclModuleForCompilation(ASTDecl &decl) {
  IRMapping mapping;
  return cloneDeclModuleForCompilation(decl, mapping);
}
OwningOpRef<ModuleOp> LIT::cloneDeclModuleForCompilation(ASTDecl &decl,
                                                         IRMapping &mapping) {
  Operation *declOp = decl.getIfOperation();
  assert(declOp && "expected decl to be an operation");

  // Clone the module containing the decl.
  ModuleOp declModule = declOp->getParentOfType<ModuleOp>();
  OwningOpRef<ModuleOp> newModule = cast<ModuleOp>(declModule->clone(mapping));
  Operation *newDeclOp = mapping.lookup(declOp);

  // Perform the necessary post-parse transformations to prepare the module for
  // compilation.
  // TODO: ensure bodies of closure traits survive resolution and remove the
  // closure preservation flag.
  eraseUnreachableDecls(newDeclOp, *newModule,
                        /*preserveClosureTraitMethods=*/false);
  sortValueUses(*newModule);

  // Give any lit.fn with an empty body region a placeholder entry block and
  // mark it external. These are lazy bytecode stubs: the LSP skips
  // resolveBody on imported FnOps to avoid pulling in expensive transitive
  // imports, so their 0-block bodies survive into the cloned module the check
  // pipeline runs on (normal compilation never sees this because
  // finalizeImportedBytecodeModules erases stubs first). The block must be
  // shaped like the real signature via addEntryBlock() -- lit.fn's body is a
  // SizedRegion<1>, and FnOp::print indexes the block's arguments per
  // parameter -- terminated by an `unresolved` lit.end_fn, the same
  // placeholder the parser emits for an unresolved body (ParserStmts.cpp).
  // The check pipeline skips external functions, so this body is never
  // lowered, only verified structurally.
  newModule->walk([](LIT::FnOp func) {
    if (!func.getBodyRegion().empty())
      return;
    func.setExternal(true);
    Block *body = func.addEntryBlock();
    OpBuilder builder = OpBuilder::atBlockEnd(body);
    LIT::EndFnOp::create(builder, func.getLoc(), /*unresolved=*/true);
  });

  return newModule;
}

//===----------------------------------------------------------------------===//
// ParserListener
//===----------------------------------------------------------------------===//

bool ParserListener::isInterestedInLoc(SMLoc parserLoc) { return true; }
void ParserListener::onAliasDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onArgumentDecl(ASTDecl *decl, StringRef argName,
                                    SMLoc identifierLoc) {}
void ParserListener::onFunctionDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onImport(SMLoc importLoc) {}
void ParserListener::onImport(ResolveInputDeclFn getPackageDecl,
                              SMLoc importLoc) {}
void ParserListener::onMemberLookup(ResolveInputDeclFn getDeclFn, SMLoc loc,
                                    bool searchParentScopes) {}
void ParserListener::onModuleImport(ASTDecl *decl, StringRef spelling,
                                    SMLoc importLoc) {}
void ParserListener::onModuleDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onParameterDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onStructDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onStructFieldDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onTraitDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onVariableDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onRef(ArrayRef<ASTDecl *> decls, StringRef spelling,
                           llvm::SMRange range) {}
void ParserListener::onCall(ArrayRef<ASTDecl *> decls, llvm::SMLoc rparenLoc,
                            const CallOperands &operands) {}
void ParserListener::onParameterBinding(ArrayRef<ASTDecl *> decls,
                                        llvm::SMLoc rsquareLoc,
                                        ArrayRef<ExprNode *> parameters) {}
