load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "config",
    srcs = ["config.py"],
    deps = [
        requirement("pydantic"),
        requirement("pydantic-settings"),
        "//max/python/max/support",
    ],
)

modular_py_library(
    name = "process_control",
    srcs = ["process_control.py"],
    deps = [
        "//max/python/max/support:taskgroups",
    ],
)

modular_py_library(
    name = "exceptions",
    srcs = ["_exceptions.py"],
)

modular_py_library(
    name = "queue",
    srcs = ["queue.py"],
)

modular_py_library(
    name = "scheduler_result",
    srcs = ["scheduler_result.py"],
    deps = [
        "//max/python/max/pipelines/modeling",
        requirement("msgspec"),
    ],
)

modular_py_library(
    name = "serve",
    srcs = glob(
        ["*.py"],
        exclude = [
            "process_control.py",
            "config.py",
            "debug.py",
            "_exceptions.py",
            "queue.py",
            "scheduler_result.py",
        ],
    ),
    deps = [
        ":config",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/serve/media",
        "//max/python/max/serve/pipelines",
        "//max/python/max/serve/recordreplay",
        "//max/python/max/serve/router",
        "//max/python/max/serve/schemas",
        "//max/python/max/serve/telemetry",
        "//max/python/max/serve/worker_interface",
        requirement("asgiref"),
        requirement("fastapi"),
        requirement("prometheus-client"),
        requirement("uvicorn"),
    ],
)

modular_py_library(
    name = "debug",
    srcs = ["debug.py"],
    deps = [
        requirement("fastapi"),
        requirement("pydantic"),
        requirement("pydantic-settings"),
        requirement("pyinstrument"),
    ],
)
