load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "router",
    srcs = glob(["*.py"]),
    deps = [
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/lora",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/pipelines/request",
        "//max/python/max/profiler",
        "//max/python/max/serve:config",
        "//max/python/max/serve/dependencies",
        "//max/python/max/serve/media",
        "//max/python/max/serve/parser",
        "//max/python/max/serve/pipelines",
        "//max/python/max/serve/schemas",
        "//max/python/max/serve/telemetry",
        "//max/python/max/serve/worker_interface",
        requirement("aiofiles"),
        requirement("fastapi"),
        requirement("opentelemetry-api"),
        requirement("httpx"),
        requirement("jinja2"),
        requirement("numpy"),
        requirement("openai"),
        requirement("pillow"),
        requirement("pydantic"),
        requirement("sse-starlette"),
        requirement("starlette"),
    ],
)
