load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "lora",
    srcs = glob(["**/*.py"]),
    test_docstring_examples = True,
    deps = [
        "//max/python/max/config",
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/experimental",
        "//max/python/max/experimental/nn",
        "//max/python/max/graph",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/pipelines/weights",
        requirement("msgspec"),
        requirement("numpy"),
        requirement("pydantic"),
    ],
)
