load("//bazel:api.bzl", "mojo_test")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS_COPTS")

package(default_visibility = ["//max:consumers"])

[
    mojo_test(
        name = src.removesuffix(".mojo") + ".test",
        size = "medium",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        tags = ["gpu"],
        target_compatible_with = ["//:nvidia_gpu"],
        deps = [
            "//max:max_mojo",
            "@mojo//:std",
        ],
    )
    for src in glob(["*.mojo"])
]
