load("//bazel:api.bzl", "mojo_test")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS_COPTS")

package(default_visibility = ["//max:consumers"])

[
    mojo_test(
        name = src + ".test",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        deps = [
            "//max:builtin_kernels",
            "//max:extensibility",
            "//max:layout",
            "@mojo//:std",
        ],
    )
    for src in glob(["**/*.mojo"])
]
