load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//Mojo:consumers"])

modular_cc_binary(
    name = "mojo-lsp-replayer",
    srcs = glob(["*.cpp"]),
    data = ["//Mojo/tools/mojo-lsp-server"],
    deps = [
        "//Mojo/tools/common/lsp-protocol",
        "//Mojo/tools/mojo-lsp-test-client",
    ],
)
