load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "minimax_music3",
    srcs = glob(["**/*.py"]),
    deps = [
        requirement("numpy"),
        requirement("transformers"),
        requirement("typing-extensions"),
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/engine",
        "//max/python/max/experimental",
        "//max/python/max/experimental/nn",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/audio",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/kv_cache",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/profiler",
    ],
)
