//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//
//
// This is the top level file for the KGEN dialect.
//
//===----------------------------------------------------------------------===//

#ifndef KGEN_KGENDIALECT_KGEN_TD
#define KGEN_KGENDIALECT_KGEN_TD

include "Mojo/KGENDialect/KGENAttrs.td"
include "Mojo/KGENDialect/KGENTypes.td"
include "Mojo/KGENDialect/KGENOps.td"

#endif // KGEN_KGENDIALECT_KGEN_TD
