load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "test_tool_parser",
    srcs = [
        "test_tool_parser.py",
    ],
    deps = [
        "//max/python/max/_xgrammar",
        "//max/python/max/pipelines/architectures/minimax_m2",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
    ],
)

modular_py_test(
    name = "test_reasoning",
    srcs = ["test_reasoning.py"],
    deps = [
        "//max/python/max/pipelines/architectures/minimax_m2",
        requirement("numpy"),
        requirement("pytest-asyncio"),
    ],
)
