load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "test_eagle3_weight_loading",
    srcs = ["test_eagle3_weight_loading.py"],
    gpu_constraints = ["//:has_gpu"] + select({
        "//:apple_gpu": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tags = ["gpu"],
    deps = [
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/deepseekV3",
        "//max/python/max/pipelines/architectures/eagle3_deepseekV3",
    ],
)

modular_py_test(
    name = "test_graph_capture_vision_inputs",
    srcs = ["test_graph_capture_vision_inputs.py"],
    deps = [
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/pipelines/architectures/kimik2_5",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        requirement("numpy"),
    ],
)

modular_py_test(
    name = "test_tool_parser",
    srcs = ["test_tool_parser.py"],
    deps = [
        "//max/python/max/_xgrammar",
        "//max/python/max/pipelines/architectures/kimik2_5",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
    ],
)

modular_py_test(
    name = "test_reasoning",
    srcs = ["test_reasoning.py"],
    target_compatible_with = select({
        "@platforms//os:macos": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),  # FIXME: MOCO-2411
    deps = [
        "//max/python/max/pipelines/architectures/kimik2_5",
        requirement("numpy"),
        requirement("pytest-asyncio"),
    ],
)

modular_py_test(
    name = "test_preprocess_cache",
    srcs = ["test_preprocess_cache.py"],
    deps = [
        "//max/python/max/pipelines/architectures/kimik2_5",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/support",
        requirement("numpy"),
        requirement("pillow"),
    ],
)

modular_py_test(
    name = "test_tokenizer",
    srcs = ["test_tokenizer.py"],
    deps = [
        "//max/python/max/pipelines/architectures/kimik2_5",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/modeling",
        requirement("pytest-asyncio"),
    ],
)
