//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

#include "MCLinker.h"
#include "LLVMAccessorHelper.h"
#include "LLVMPassesPipeline.h"
#include "Mojo/Compiler/Target/TargetBackend.h"
#include "llvm/Analysis/RuntimeLibcallInfo.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Linker/Linker.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/Triple.h"

using namespace M;
using namespace KGEN;

void SymbolAndMCInfo::clear() {
  symbolLinkageTypes.clear();
  mcInfos.clear();
}

MCLinker::MCLinker(
    SmallVectorImpl<SymbolAndMCInfo *> &symbolAndMCInfos,
    llvm::TargetMachine &targetMachine, CompilationOptions options,
    llvm::StringMap<llvm::GlobalValue::LinkageTypes> symbolLinkageTypes,
    llvm::StringMap<unsigned> originalFnOrdering)
    : symbolAndMCInfos(symbolAndMCInfos), targetMachine(targetMachine),
      options(std::move(options)),
      symbolLinkageTypes(std::move(symbolLinkageTypes)),
      originalFnOrdering(std::move(originalFnOrdering)) {

  llvm::TargetMachine &llvmTargetMachine =
      static_cast<llvm::TargetMachine &>(targetMachine);

  machineModInfoPass =
      new llvm::MachineModuleInfoWrapperPass(&llvmTargetMachine);
}

ErrorOrSuccess MCLinker::linkLLVMModules(StringRef moduleName) {
  ErrorOrSuccess createModuleResult =
      linkedModule.create([&](llvm::LLVMContext &ctx) {
        return std::make_unique<llvm::Module>(moduleName, ctx);
      });

  if (createModuleResult.isError())
    return Error("failed to create an empty LLVMModule for MCLinker");

  llvm::Linker linker(*linkedModule);
  llvm::StringMap<llvm::GlobalValue::LinkageTypes> newSymbolLinkageTypes;

  unsigned curCompileUnitIdx = 0;
  for (auto [i, smcInfos] : llvm::enumerate(symbolAndMCInfos)) {
    for (auto &[key, value] : smcInfos->symbolLinkageTypes)
      symbolLinkageTypes.insert({key, value});

    for (auto [j, mcInfo] : llvm::enumerate(smcInfos->mcInfos)) {
      mcInfos.push_back(mcInfo.get());
      ++curCompileUnitIdx;

      // Modules have to be in the same LLVMContext to be linked.
      llvm::Expected<std::unique_ptr<llvm::Module>> moduleOr =
          llvm::parseBitcodeFile(
              llvm::MemoryBufferRef(
                  StringRef(mcInfo->moduleBuf->getBufferStart(),
                            mcInfo->moduleBuf->getBufferSize()),
                  ""),
              linkedModule->getContext());
      if (!moduleOr)
        return Error("failed to serialize post-llc modules");

      std::unique_ptr<llvm::Module> module = std::move(moduleOr.get());
      for (auto &func : module->functions()) {
        // [MOCO-1751] If the function was generated by LLVM's backend with a
        // private linkage, linker will rename the function if there's a
        // conflict, which can cause ICE (Internal Compiler Error) in AsmPrinter
        // that tries to find MachineFunction for the resolved name.
        // Don't immediately update symbolLinkageTypes as it will conflict with
        // other modules that have same functions.
        //
        // NOTE: A bit more accurate fix would be to do that iff the symbol is
        // used in multiple modules. Also, need to check that the function was
        // constructed by the backend.
        //
        // NOTE: The ICE is this case is non-obvious and usually looks as
        // MF->front() doesn't exist in places where it should.
        if (!symbolLinkageTypes.contains(func.getName().str()) &&
            func.hasPrivateLinkage()) {
          newSymbolLinkageTypes.insert(
              {func.getName().str(), func.getLinkage()});
          func.setLinkage(llvm::GlobalValue::WeakAnyLinkage);
        }
      }

      for (auto &global : module->globals()) {
        // Codegen-emitted local-linkage globals (private or internal) can
        // collide by name across splits and get renamed at link time. Rename
        // and record it here so the MachineFunction use is updated to match.
        if (!symbolLinkageTypes.contains(global.getName().str()) &&
            global.hasLocalLinkage()) {
          // Uniquifying the name using a global index.
          std::string originalName = global.getName().str();
          std::string uniqueName =
              (originalName + "_" + Twine(curCompileUnitIdx)).str();
          mcInfo->renamedLocalSymbols.insert({originalName, uniqueName});

          // Set to new name.
          global.setName(uniqueName);
        }
      }

      if (linker.linkInModule(std::move(module)))
        return Error("failed to link post-llc modules");
      mcInfo->mcContext->setUseNamesOnTempLabels(true);
    }
  }

  // Now it's time to update the table to include the new symbols that were
  // modified.
  for (auto &[key, value] : newSymbolLinkageTypes)
    symbolLinkageTypes.insert({key, value});

  // Restore linkage type.
  for (llvm::GlobalValue &global : linkedModule->globals()) {
    if (!global.hasWeakLinkage())
      continue;
    auto iter = symbolLinkageTypes.find(global.getName().str());
    if (iter == symbolLinkageTypes.end())
      continue;

    global.setLinkage(iter->second);
    global.setDSOLocal(true);
  }

  for (llvm::Function &fn : linkedModule->functions()) {
    if (!fn.hasWeakLinkage())
      continue;

    auto iter = symbolLinkageTypes.find(fn.getName().str());
    if (iter == symbolLinkageTypes.end())
      continue;

    fn.setLinkage(iter->second);
    fn.setDSOLocal(true);
  }

  return {};
}

void MCLinker::prepareMachineModuleInfo(
    llvm::TargetMachine &llvmTargetMachine) {

  // Helper lambda to traverse all GlobalAddress operands in the
  // MachineFunction.
  auto foreachGAMachineOperand =
      [](llvm::MachineFunction &mf,
         llvm::function_ref<void(llvm::MachineOperand &)> func) {
        for (auto &bb : mf) {
          for (auto &mi : bb) {
            llvm::for_each(
                llvm::make_filter_range(
                    mi.operands(),
                    [](llvm::MachineOperand &mo) { return mo.isGlobal(); }),
                func);
          }
        }
      };

  for (auto [i, smcInfos] : llvm::enumerate(symbolAndMCInfos)) {
    for (auto [j, mcInfo] : llvm::enumerate(smcInfos->mcInfos)) {
      // Move MachineFunctions from each split's codegen result
      // into machineModInfoPass to print out together in one .o
      llvm::DenseMap<const llvm::Function *,
                     std::unique_ptr<llvm::MachineFunction>> &machineFunctions =
          getMachineFunctionsFromMachineModuleInfo(*mcInfo->machineModuleInfo);

      llvm::StringMap<const llvm::Function *> &fnNameToFnPtr =
          mcInfo->fnNameToFnPtr;

      mcInfo->machineModuleInfo->getContext().setObjectFileInfo(
          llvmTargetMachine.getObjFileLowering());

      for (auto &fn : linkedModule->functions()) {
        if (fn.isDeclaration())
          continue;
        if (machineModInfoPass->getMMI().getMachineFunction(fn))
          continue;

        auto fnPtrIter = fnNameToFnPtr.find(fn.getName().str());
        if (fnPtrIter == fnNameToFnPtr.end())
          continue;
        auto mfPtrIter = machineFunctions.find(fnPtrIter->second);
        if (mfPtrIter == machineFunctions.end())
          continue;

        llvm::Function &origFn = mfPtrIter->second->getFunction();
        std::unique_ptr<llvm::MachineFunction> mf =
            std::move(mfPtrIter->second);

        // Each split module lives in its own LLVMContext, so the same
        // personality function is a different GlobalValue* across splits.
        // Redirect to the linked-module's canonical pointer so pointer-based
        // deduplication in DwarfCFIException::addPersonality works correctly.
        if (fn.hasPersonalityFn())
          origFn.setPersonalityFn(fn.getPersonalityFn());

        const auto &renamedGVs = mcInfo.get()->renamedLocalSymbols;
        if (!renamedGVs.empty()) {
          foreachGAMachineOperand(*mf, [&](llvm::MachineOperand &mo) {
            auto it = renamedGVs.find(mo.getGlobal()->getName());
            if (it != renamedGVs.end()) {
              mo.ChangeToGA(linkedModule->getNamedGlobal(it->second),
                            mo.getOffset(), mo.getTargetFlags());
            }
          });
        }

        machineModInfoPass->getMMI().insertFunction(fn, std::move(mf));

        // Restore function linkage types.
        if (!origFn.hasWeakLinkage())
          continue;

        auto iter = symbolLinkageTypes.find(fn.getName().str());
        if (iter == symbolLinkageTypes.end())
          continue;

        origFn.setLinkage(iter->second);
        origFn.setDSOLocal(true);
      }

      // Restore global variable linkage types.
      for (auto &global : mcInfo->moduleAndContext->globals()) {
        if (!global.hasWeakLinkage())
          continue;
        auto iter = symbolLinkageTypes.find(global.getName().str());
        if (iter == symbolLinkageTypes.end())
          continue;

        global.setLinkage(iter->second);
        global.setDSOLocal(true);
      }

      // Release memory as soon as possible to reduce peak memory footprint.
      mcInfo->machineModuleInfo.reset();
      mcInfo->fnNameToFnPtr.clear();
      mcInfo->moduleBuf.reset();
    }
  }
}

llvm::Module *
MCLinker::getModuleToPrintOneSplit(llvm::TargetMachine &llvmTargetMachine) {
  auto &mcInfo = symbolAndMCInfos[0]->mcInfos[0];

  llvm::DenseMap<const llvm::Function *, std::unique_ptr<llvm::MachineFunction>>
      &machineFunctions =
          getMachineFunctionsFromMachineModuleInfo(*mcInfo->machineModuleInfo);

  mcInfo->machineModuleInfo->getContext().setObjectFileInfo(
      llvmTargetMachine.getObjFileLowering());

  for (auto &fn : mcInfo->moduleAndContext->functions()) {
    if (fn.isDeclaration())
      continue;

    auto mfPtrIter = machineFunctions.find(&fn);
    if (mfPtrIter == machineFunctions.end())
      continue;

    machineModInfoPass->getMMI().insertFunction(fn,
                                                std::move(mfPtrIter->second));
  }

  mcInfo->mcContext->setUseNamesOnTempLabels(true);
  // Release memory as soon as possible to reduce peak memory footprint.
  mcInfo->machineModuleInfo.reset();
  mcInfo->fnNameToFnPtr.clear();
  mcInfo->moduleBuf.reset();
  return &(*mcInfo->moduleAndContext);
}

ErrorOr<WriteableBufferRef> MCLinker::linkAndPrint(StringRef moduleName,
                                                   bool emitAssembly) {

  llvm::TargetMachine &llvmTargetMachine =
      static_cast<llvm::TargetMachine &>(targetMachine);

  llvmTargetMachine.Options.MCOptions.AsmVerbose = options.verboseOutput;
  llvmTargetMachine.Options.MCOptions.PreserveAsmComments =
      options.verboseOutput;

  bool hasOneSplit =
      symbolAndMCInfos.size() == 1 && symbolAndMCInfos[0]->mcInfos.size() == 1;

  ErrorOr<const TargetBackend *> backendOr =
      TargetBackendRegistry::get().lookup(llvm::Triple(options.targetTriple));
  const TargetBackend *backend = backendOr.isError() ? nullptr : *backendOr;

  llvm::Module *oneSplitModule = nullptr;

  if (!hasOneSplit) {
    // Backends that share one llvm::Module across llvm-opt and llc (e.g. NVPTX,
    // for its AnnotationCache) cannot operate on multiple splits here.
    if (backend && backend->requiresSingleModuleSplit())
      return Error("single-module-split backend unexpectedly has multiple "
                   "splits.");

    // link at llvm::Module level.
    ErrorOrSuccess lmResult = linkLLVMModules(moduleName);
    if (lmResult.isError())
      return Error(lmResult.getError());

    prepareMachineModuleInfo(llvmTargetMachine);

    // The Linker may change function ordering in the linkedModule; some
    // backends (e.g. NVPTX) need it restored to the original order so function
    // declarations precede uses. No-op for backends that don't care.
    if (backend)
      backend->reorderLinkedModuleFunctions(*linkedModule, originalFnOrdering);
  } else {
    oneSplitModule = getModuleToPrintOneSplit(llvmTargetMachine);
    oneSplitModule->setModuleIdentifier(moduleName);
  }

  // Prepare AsmPrint pipeline.
  WriteableBufferRef linkedObj = WriteableBuffer::get();

  llvm::legacy::PassManager passMgr;
  // Add an appropriate TargetLibraryInfo pass for the module's triple.
  llvm::TargetLibraryInfoImpl targetLibInfo(llvm::Triple(options.targetTriple));

  // Add AsmPrint pass and run the pass manager.
  passMgr.add(new llvm::TargetLibraryInfoWrapperPass(targetLibInfo));

  // Add RuntimeLibraryInfoWrapper for libcall lowering decisions.
  // This is required by passes like ExpandFp and PreISelIntrinsicLowering.
  const llvm::TargetOptions &tmOptions = llvmTargetMachine.Options;
  passMgr.add(new llvm::RuntimeLibraryInfoWrapper(
      tmOptions.ExceptionModel, tmOptions.EABIVersion,
      tmOptions.MCOptions.ABIName, tmOptions.VecLib));

  if (KGEN::addPassesToAsmPrint(options, llvmTargetMachine, passMgr, *linkedObj,
                                emitAssembly
                                    ? llvm::CodeGenFileType::AssemblyFile
                                    : llvm::CodeGenFileType::ObjectFile,
                                true, machineModInfoPass, mcInfos)) {
    // Release some of the AsyncValue memory to avoid
    // wrong version of LLVMContext destructor being called due to
    // multiple LLVM being statically linked in dylibs that have
    // access to this code path.
    for (SymbolAndMCInfo *smcInfo : symbolAndMCInfos)
      smcInfo->clear();

    return Error("failed to add to ObjectFile Print pass");
  }

  const_cast<llvm::TargetLoweringObjectFile *>(
      llvmTargetMachine.getObjFileLowering())
      ->Initialize(machineModInfoPass->getMMI().getContext(), targetMachine);

  llvm::Module &moduleToRun = hasOneSplit ? *oneSplitModule : *linkedModule;
  passMgr.run(moduleToRun);

  // Release some of the AsyncValue memory to avoid
  // wrong version of LLVMContext destructor being called due to
  // multiple LLVM being statically linked in dylibs that have
  // access to this code path.
  for (SymbolAndMCInfo *smcInfo : symbolAndMCInfos)
    smcInfo->clear();

  return linkedObj;
}
