load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "tests",
    size = "large",
    srcs = glob(
        [
            "*.py",
            "audio_generation/*.py",
            "pixel_generation/*.py",
            "text_generation/*.py",
        ],
    ),
    deps = [
        "//max/python/max:_core",
        "//max/python/max/pipelines/audio",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/pipelines/request",
        "//max/python/max/serve:queue",
        "//max/python/max/support",
        requirement("msgspec"),
        requirement("numpy"),
        requirement("pillow"),
        requirement("pydantic"),
        requirement("pytest-asyncio"),
    ],
)
