load("//bazel:api.bzl", "modular_py_library", "mojo_shared_library")

package(default_visibility = ["//max:consumers"])

mojo_shared_library(
    name = "kv_cache_ops",
    srcs = ["kv_cache_ops.mojo"],
    data = [
        "@mojo//:python",
    ],
    shared_lib_name = "kv_cache_ops.so",
    deps = [
        "//max:nn",
        "@mojo//:std",
    ],
)

modular_py_library(
    name = "_kv_cache_ops",
    srcs = ["__init__.py"],
    data = [":kv_cache_ops"],
    ignore_unresolved_imports = [
        # mojo.importer populates these symbols from the native extension.
        ".kv_cache_ops.mha_decode_num_partitions",
        ".kv_cache_ops.mla_dispatch_args_scalar",
    ],
    deps = [
        "//max/python/max/driver",
        "@mojo//:python",
    ],
)
