[workspace]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Introduction to Mojo Tutorial: Conway's Game of Life"
name = "life"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
mojo = "*"
python = ">=3.11,<3.14"

[pypi-dependencies]
pygame-ce = ">=2.5.6,<3"

[tasks]
lifev1 = "mojo run lifev1.mojo"
lifev2 = "mojo run lifev2.mojo"
main = "mojo run benchmark.mojo"
benchmark = "mojo run benchmark.mojo"
test_gridv1 = "mojo run -I . test/test_gridv1.mojo"
test_gridv2 = "mojo run -I . test/test_gridv2.mojo"
test = { depends-on = ["test_gridv1", "test_gridv2"] }
