load("//bazel:api.bzl", "modular_cc_binary")

package(
    default_visibility = ["//visibility:public"],
    features = [
        "layering_check",
        "parse_headers",
    ],
)

modular_cc_binary(
    name = "driver-tblgen",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
    deps = [
        "//Support:Base",
        "@llvm-project//llvm:Support",
        "@llvm-project//llvm:TableGen",
    ],
)
