load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "multi-gpu-tests",
    size = "large",
    srcs = glob(
        ["*.py"],
    ),
    exec_properties = {
        "test.resources:gpu-memory": "3",
    },
    gpu_constraints = ["//:has_multi_gpu"],
    tags = ["gpu"],
    deps = [
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/engine",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/support",
        requirement("ml-dtypes"),
        requirement("numpy"),
        requirement("torch"),
    ],
)
