//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//
//
// This pass walks parameter expressions within the bodies of functions and
//   lifts and deduplicates visited 'apply' operators to `kgen.param.apply`
//   operations within the function body. This enables the elaborator to
//   multi-version generators from 'apply' operators whose callee has multiple
//   candidates.
//
//   This pass also attempts to interpret 'apply' operators on constant inputs
//   on non-parametric callees.
//
//   Note that the IR generated by this pass may not pass `verify-parameters`.
//   This is because by modifying 'apply' operators within call operations, it
//   can create concrete signatures that disagree with what the standard
//   `ParameterEvaluator` determines as the concrete signature for a callee.
//
//===----------------------------------------------------------------------===//

#include "Mojo/KGENDialect/KGENOps.h"
#include "Mojo/KGENDialect/KGENParameters.h"
#include "Mojo/KGENDialect/ParameterEvaluator.h"
#include "Mojo/Support/CompilerProfiling.h"
#include "Mojo/ToolCommon/KGENPasses.h"
#include "Support/Compiler/Threading.h"
#include "mlir/Analysis/SymbolTableAnalysis.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "llvm/Support/Mutex.h"

using namespace M;
using namespace KGEN;

namespace M::KGEN {
#define GEN_PASS_DEF_LIFTANDFOLDAPPLY
#include "Mojo/KGENPasses.h.inc"
} // namespace M::KGEN

using LiftedMapStack =
    SmallVector<std::pair<Region *, DenseMap<ParamOperatorAttr, Attribute>>>;

/// Recursively lift and fold apply operators within the provided body.
static void liftAndFoldApply(Region *body, ImplicitLocOpBuilder &b,
                             ParameterCollector &collector,
                             LiftedMapStack &lifted, unsigned &counter,
                             const ParameterUseDefGraph &graph,
                             const ParameterUseDefGraph &topLevel,
                             unsigned &numDedupedApplies) {
  mlir::AttrTypeReplacer replacer;
  lifted.emplace_back().first = body;

  // Skip over parameter scopes. We cannot generically pull out 'apply'
  // operators from within attr/types that define parameter scopes because the
  // parameter expressions may reference scoped parameter decls.
  replacer.addReplacement([](ParameterScopeTypeInterface scopeType) {
    if (scopeType.getInputParamTypes().empty())
      return std::make_pair(scopeType, WalkResult::advance());
    return std::make_pair(scopeType, WalkResult::skip());
  });
  replacer.addReplacement([](ParameterScopeAttrInterface scopeAttr) {
    if (scopeAttr.getInputParamTypes().empty())
      return std::make_pair(scopeAttr, WalkResult::advance());
    return std::make_pair(scopeAttr, WalkResult::skip());
  });

  replacer.addReplacement([&](BindParamsAttr attr)
                              -> std::pair<TypedAttr, WalkResult> {
    TypedAttr generator =
        cast<TypedAttr>(replacer.replace(attr.getGenerator()));

    ParameterEvaluator evaluator;
    for (auto [idx, paramValue] : llvm::enumerate(attr.getParamValues())) {
      TypedAttr value = cast<TypedAttr>(replacer.replace(paramValue));
      Type targetType = evaluator.replace(
          cast<GeneratorType>(generator.getType()).getInputParamTypes()[idx]);
      // Lifting may change the type of a parameter value, creating temporary
      // illegal IR. Rebind it back to the original, correct type if this
      // happened so that BindParamsAttr can still infer the result type
      // correctly.
      if (value.getType() != targetType)
        value = ParamOperatorAttr::getRebind(value, targetType);
      evaluator.appendIndexBinding(value);
    }

    return {BindParamsAttr::get(generator.getContext(), generator,
                                evaluator.getIndexBindings(),
                                attr.getDischarged()),
            WalkResult::skip()};
  });

  replacer.addReplacement([&](ParamOperatorAttr op)
                              -> std::pair<Attribute, WalkResult> {
    // Expressions cannot be hoisted out of a condition because it only
    // conditionally evaluates both branches. Moving expressions out changes the
    // semantics of the program.
    if (op.getOpcode() == POC::Cond)
      return {op, WalkResult::skip()};

    if (op.getOpcode() != POC::Apply)
      return {op, WalkResult::advance()};

    // When we encounter an 'apply' operator, check the lifted map for this
    // scope for an operator of the same value in the current scope that has
    // already been lifted.
    DenseMap<ParamOperatorAttr, Attribute> &curMap = lifted.back().second;
    if (auto it = curMap.find(op); it != curMap.end()) {
      // Deduplicated an 'apply'.
      ++numDedupedApplies;
      return {it->second, WalkResult::advance()};
    }

    // Collect all parameter uses within the operator so we can check the
    // declaring operations to determine the highest scope into which we could
    // lift this operator.
    SmallVector<ParamDeclRefAttr> uses;
    bool hasConstExpr = false;
    size_t requiredSignatureDepth = 0;
    collector.collectUsesFromAttr(op, uses, hasConstExpr,
                                  requiredSignatureDepth);

    // Baseline is the top-level scope, which would be valid for empty uses.
    Region *upperBound = topLevel.scope;

    for (ParamDeclRefAttr use : uses) {
      const ParamDeclaration &decl = graph.decls.at(use.getName());
      if (upperBound->isProperAncestor(decl.scope))
        upperBound = decl.scope;
    }

    // Walk backwards starting from the next-nearest scope to determine the
    // lowest scope in which this operator has been lifted. This is important
    // because we don't want to hoist invalid operators out of conditionals.
    Attribute existing;
    for (std::pair<Region *, DenseMap<ParamOperatorAttr, Attribute>> &frame :
         llvm::reverse(lifted)) {
      // Skip the current scope.
      if (frame.first != body) {
        // Look for a lifted operator in this scope's cache.
        if (auto it = frame.second.find(op); it != frame.second.end()) {
          existing = it->second;
          break;
        }
      }
      // Stop once we reach the upper bound.
      if (frame.first == upperBound)
        break;
    }

    // If we didn't find an existing lifted operator, then lift the operator at
    // the current scope.
    if (!existing) {
      // Explicit recurse on the operator.
      Type type = replacer.replace(op.getType());
      TypedAttr callee =
          cast<TypedAttr>(replacer.replace(op.getOperands().front()));
      SmallVector<TypedAttr> operands;
      for (TypedAttr operand : op.getOperands().drop_front())
        operands.push_back(cast<TypedAttr>(replacer.replace(operand)));

      // Generate a name for the lifted parameter.
      auto decl = ParamDeclAttr::get(
          b.getStringAttr("(lifted)apply_" + Twine(counter++)), type);

      // Create the operation and set the value of the lifted operator.
      ParamApplyOp::create(b, decl, callee, operands);
      existing = ParamDeclRefAttr::get(decl);
    } else {
      // Deduplicated an 'apply' with the existing parameter.
      ++numDedupedApplies;
    }

    // Map the created or existing parameter into the current scope. This also
    // has the effect of allowing searches for the same operator to end early in
    // nested scopes.
    curMap.try_emplace(op, existing);
    return {existing, WalkResult::advance()};
  });

  if (auto func = dyn_cast<GeneratorOp>(body->getParentOp())) {
    b.setLoc(func.getLoc());
    b.setInsertionPointToStart(func.getBody());
    replacer.replaceElementsIn(func, /*replaceAttrs=*/false,
                               /*replaceLocs=*/true, /*replaceTypes=*/true);
    // Certain generator attributes need to be evaluatable in isolation.
    // Specially handle them here.
    NamedAttrList attrs = func->getAttrDictionary();
    attrs.set(func.getFunctionTypeAttrName(),
              replacer.replace(func.getFunctionTypeAttr()));
    attrs.set(func.getInputParamsAttrName(),
              replacer.replace(func.getInputParamsAttr()));
    attrs.set(func.getDecoratorsAttrName(),
              replacer.replace(func.getDecoratorsAttr()));
    func->setAttrs(attrs.getDictionary(func.getContext()));
  }

  bool insertPointSet = false;

  // Extract 'apply' operators and place them
  // at the start of the parent region if parent is a GeneratorOp
  // or DeclInterface. This essentially to place them at the beginning
  // of its param decl region.
  if (auto gen = dyn_cast<GeneratorOp>(body->getParentOp())) {
    b.setLoc(gen.getLoc());
    b.setInsertionPointToStart(gen.getBody());
    insertPointSet = true;
  } else if (auto parent = body->getParentOfType<DeclInterface>()) {
    for (Region &region : parent->getRegions()) {
      if (region.isAncestor(body)) {
        // Find the parent DeclInterface's region and set the insertion point
        // at the beginning of the region.
        b.setLoc(parent.getLoc());
        b.setInsertionPointToStart(&region.getBlocks().front());
        insertPointSet = true;
        break;
      }
    }
  }

  body->walk<mlir::WalkOrder::PreOrder>([&](Operation *op) {
    if (!insertPointSet) {
      // Insert the apply operations as close to the original location of the
      // 'apply' operator as possible,
      // if the insertion point is not already set.
      b.setLoc(op->getLoc());
      b.setInsertionPoint(op);
    }

    replacer.replaceElementsIn(op, /*replaceAttrs=*/true, /*replaceLocs=*/true,
                               /*replaceTypes=*/true);

    // Walk over nested parameter scopes, since lifted apply operators with name
    // shadowing can cause collisions.
    if (isa<DeclInterface>(op)) {
      for (Region &region : op->getRegions()) {
        ImplicitLocOpBuilder b(body->getParentOp()->getLoc(),
                               OpBuilder(body->getContext()));

        liftAndFoldApply(&region, b, collector, lifted, counter,
                         topLevel.nestedScopes.at(&region), topLevel,
                         numDedupedApplies);
      }
      return WalkResult::skip();
    }
    return WalkResult::advance();
  });

  lifted.pop_back();
}

/// Entry point for `liftAndFoldApply`. This function keeps a cache of lifted
/// operators for each scope.
static void liftAndFoldApply(Region *body,
                             ParameterCollector::Analysis &paramCache,
                             const ParameterUseDefGraph &topLevel,
                             unsigned &numDedupedApplies) {
  ImplicitLocOpBuilder b(body->getParentOp()->getLoc(),
                         OpBuilder(body->getContext()));
  LiftedMapStack lifted;
  unsigned counter = 0;
  ParameterCollector collector(paramCache);
  liftAndFoldApply(body, b, collector, lifted, counter, topLevel, topLevel,
                   numDedupedApplies);
}

namespace {
struct LiftAndFoldApplyPass : impl::LiftAndFoldApplyBase<LiftAndFoldApplyPass> {
  using LiftAndFoldApplyBase::LiftAndFoldApplyBase;

  void runOnOperation() override {
    auto &paramCache = getAnalysis<ParameterCollector::Analysis>();
    // Sum the number of deduplicated operators over all work items.
    std::atomic<unsigned> totNumDedupedApplies = 0;

    auto workFunc = [&totNumDedupedApplies](auto &cache, GeneratorOp func) {
      ParameterUseDefGraph graph(func.getBodyRegion());
      graph.calculate(cache);
      unsigned numDedupedApplies = 0;
      liftAndFoldApply(&func.getBodyRegion(), cache, graph, numDedupedApplies);
      totNumDedupedApplies += numDedupedApplies;
    };

    std::vector<GeneratorOp> work;
    llvm::append_range(work, getOperation().getOps<GeneratorOp>());
    parallelForEach(&getContext(), work, workFunc, paramCache);

    // This effectively disable the verifier, because MLIR assumes that
    // if the pass said that it preserved all analyses then it can't have
    // permuted the IR. Hence no need to verify.
    // This pass mutates the IR that will fail verifier :-(.
    markAllAnalysesPreserved();

    numDedupedApplies = totNumDedupedApplies;
  }
};
} // namespace
