load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "mojo-importer",
    srcs = glob(["*.py"]),
    data = glob(["*.mojo"]),
    mojo_deps = [
        "//max:max_mojo",
        "@mojo//:std",
    ],
    target_compatible_with = select({
        "//:asan_macos": ["@platforms//:incompatible"],
        "//:tsan": ["@platforms//:incompatible"],
        "//:ubsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "@mojo//:python",
        requirement("numpy"),
    ],
)
