name: Modular CLI issue
description: Create an issue for the Modular CLI tool.
title: "[Modular CLI]"
labels:
  - "modular-cli,mojo-repo"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out an issue report!

        Please provide a descriptive title above and fill in the following fields.

  - type: textarea
    id: Description
    attributes:
      label: Issue description
      description: Describe the issue you encountered and what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: Steps
    attributes:
      label: Steps to reproduce
      description: Provide the specific steps to reproduce the issue.
      value: |
        - Include relevant code snippet that did not work as expected.
        - If applicable, add screenshots to help explain the problem.
        - Include anything else that might help us debug the issue.
    validations:
      required: true

  - type: textarea
    id: Context
    attributes:
      label: Version Info
      description: Which version of the Modular CLI are you using ?
      value: |
        - Provide Modular CLI version by pasting the output of `modular -v`
        - What OS did you install modular CLI on ?
      render: shell
