name: Mojo bug report
description: Create a bug report to help us improve Mojo
title: "[BUG]"
labels:
  - "bug,mojo-repo"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!

        Please provide a descriptive title above and fill in the following fields.

  - type: textarea
    id: Description
    attributes:
      label: Bug description
      description: Describe the bug you encountered and what you expected to happen.
      value: |
        ### Actual behavior
        <!-- Add a clear and concise description of what actually happened. -->

        ### Expected behavior
        <!-- Add a clear and concise description of what you expected to happen. -->
    validations:
      required: true

  - type: textarea
    id: Steps
    attributes:
      label: Steps to reproduce
      description: Provide the specific steps to reproduce the issue.
      value: |
        - Provide a relevant code snippet or a link to the code that did not work as expected.
        - If applicable, add screenshots to help explain the problem.
        - If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
        - Include anything else that might help us debug the issue.
    validations:
      required: true

  - type: textarea
    id: Context
    attributes:
      label: System information
      description: What version of Mojo are you using?
      value: |
        - What OS did you install Mojo on?
        - Provide version information for Mojo by pasting the output of `mojo -v`.
        - Provide the Modular CLI version by pasting the output of `modular -v`.
