load("//bazel:api.bzl", "modular_cc_binary")

package(
    default_visibility = ["//visibility:public"],
    features = [
        "layering_check",
        "parse_headers",
    ],
)

modular_cc_binary(
    name = "build-info",
    srcs = glob(["*.cpp"]),
    deps = [
        "//Support:Base",
        "//Support:BuildInfo",
        "@llvm-project//llvm:Support",
    ],
)
