//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

#ifndef KGEN_LIB_MOJOLLDB_EXPRESSIONPARSER_JITEXECUTIONUNIT_H
#define KGEN_LIB_MOJOLLDB_EXPRESSIONPARSER_JITEXECUTIONUNIT_H

#include "../Utils/Binary.h"

#include "Mojo/KGENDialect/KGENUtils.h"
#include "Support/LLVMCompilerForwardDecls.h"
#include "Support/LLVMForwardDecls.h"
#include "lldb/Expression/IRMemoryMap.h"
#include "lldb/Expression/ObjectFileJIT.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/lldb-forward.h"
#include "lldb/lldb-private.h"
#include "llvm/ExecutionEngine/ObjectCache.h"
#include "llvm/ExecutionEngine/SectionMemoryManager.h"
#include "llvm/Object/Archive.h"
#include <atomic>
#include <memory>
#include <string>
#include <vector>

namespace M::KGEN::Mojo {
/// This class contains the standalone archive and JIT-compiled code for a
/// parsed Mojo module.
///
/// This class encapsulates the compiled version of an expression in raw machine
/// code form (for execution in the target).
///
/// This object wraps a parsed module and archive that comes from the expression
/// parser, and knows how to use the JIT to turn those into executable code.  It
/// can then be used as input to the IR interpreter, or the address of the
/// executable code can be passed to a thread plan to run in the target.
///
/// This class creates a subclass of LLVM's SectionMemoryManager, because that
/// is how the JIT emits code.  Because LLDB needs to move JIT-compiled code
/// into the target process, this class knows how to copy the emitted code into
/// the target process.
class JITExecutionUnit : public std::enable_shared_from_this<JITExecutionUnit>,
                         public lldb_private::IRMemoryMap,
                         public lldb_private::ObjectFileJITDelegate {
public:
  JITExecutionUnit(SymbolTable symbolTable, ExportMap exportedSymbols,
                   OwningBinary<llvm::object::Binary> object,
                   lldb_private::ConstString &name,
                   const lldb::TargetSP &target,
                   const lldb_private::SymbolContext &symCtx,
                   std::vector<std::string> &cpuFeatures);
  ~JITExecutionUnit() override;

  lldb_private::ConstString getFunctionName();

  //===--------------------------------------------------------------------===//
  // Compilation
  //===--------------------------------------------------------------------===//

  /// Lazily compiles the expression entry point in the archive this execution
  /// unit was instantiated with, and populates the given `funcAddr` and
  /// `funcEnd` with its start and end (inclusive) addresses.
  lldb_private::Status getRunnableInfo(lldb::addr_t &funcAddr,
                                       lldb::addr_t &funcEnd);

  //===--------------------------------------------------------------------===//
  // JIT Symbols
  //===--------------------------------------------------------------------===//

  /// Encapsulates a single entity that has been generated by the JIT. Entities
  /// that have been generated by the JIT are first resident in the local
  /// process, and then placed in the target process. JittedEntity represents an
  /// entity possibly resident in both.
  struct JittedEntity {
    JittedEntity(const char *name,
                 lldb::addr_t localAddr = LLDB_INVALID_ADDRESS,
                 lldb::addr_t remoteAddr = LLDB_INVALID_ADDRESS)
        : name(name), localAddr(localAddr), remoteAddr(remoteAddr) {}

    /// The name of the entity.
    lldb_private::ConstString name;
    /// The address of the entity in LLDB's memory.
    lldb::addr_t localAddr;
    /// The address of the entity in the target's memory.
    lldb::addr_t remoteAddr;
  };
  /// A function generated by the JIT. In addition to its name and addresses,
  /// this also tracks whether the function is external (that is, whether it has
  /// non-local linkage).
  struct JittedFunction : JittedEntity {
    JittedFunction(const char *name, bool external,
                   lldb::addr_t localAddr = LLDB_INVALID_ADDRESS,
                   lldb::addr_t remoteAddr = LLDB_INVALID_ADDRESS)
        : JittedEntity(name, localAddr, remoteAddr), external(external) {}
    bool external;
  };
  /// A global variable generated by the JIT.
  struct JittedGlobalVariable : JittedEntity {
    using JittedEntity::JittedEntity;
  };

  ArrayRef<JittedFunction> getJittedFunctions();
  ArrayRef<JittedGlobalVariable> getJittedGlobalVariables();

  lldb::addr_t findSymbol(lldb_private::ConstString name, bool &missingWeak);

  //===--------------------------------------------------------------------===//
  // ObjectFileJITDelegate
  //===--------------------------------------------------------------------===//

  lldb::ByteOrder GetByteOrder() const override;

  uint32_t GetAddressByteSize() const override;

  void PopulateSymtab(lldb_private::ObjectFile *objFile,
                      lldb_private::Symtab &symtab) override {}

  void PopulateSectionList(lldb_private::ObjectFile *objFile,
                           lldb_private::SectionList &sectionList) override;

  lldb_private::ArchSpec GetArchitecture() override;

  lldb::TargetSP GetTargetSP() override { return GetTarget(); }

private:
  //===--------------------------------------------------------------------===//
  // JIT Symbols
  //===--------------------------------------------------------------------===//

  lldb::addr_t
  findInSymbols(const std::vector<lldb_private::ConstString> &names,
                const lldb_private::SymbolContext &sc,
                bool &symbolWasMissingWeak);
  lldb::addr_t
  findInRuntimes(const std::vector<lldb_private::ConstString> &names,
                 const lldb_private::SymbolContext &sc);
  lldb::addr_t
  findInUserDefinedSymbols(const std::vector<lldb_private::ConstString> &names,
                           const lldb_private::SymbolContext &sc);
  void reportSymbolLookupError(lldb_private::ConstString name);

  //===--------------------------------------------------------------------===//
  // Allocation
  //===--------------------------------------------------------------------===//

  using AddrRange = std::pair<lldb::addr_t, uintptr_t>;

  /// Encapsulates a single allocation request made by the JIT.
  ///
  /// Allocations made by the JIT are first queued up and then applied in bulk
  /// to the underlying process.
  struct AllocationRecord {
    AllocationRecord(uintptr_t hostAddress, uint32_t permissions,
                     lldb::SectionType sectType, size_t size,
                     unsigned alignment, unsigned sectionId, const char *name)
        : name((name && name[0]) ? name : ""), hostAddress(hostAddress),
          permissions(permissions), sectType(sectType), size(size),
          alignment(alignment), sectionId(sectionId) {}

    /// Dump the allocation record to the given log.
    void dump(lldb_private::Log *log);

    std::string name;
    lldb::addr_t processAddress = LLDB_INVALID_ADDRESS;
    uintptr_t hostAddress;
    uint32_t permissions;
    lldb::SectionType sectType;
    size_t size;
    unsigned alignment;
    unsigned sectionId;
  };

  /// Look up the object in m_address_map that contains a given address, find
  /// where it was copied to, and return the remote address at the same offset
  /// into the copied entity
  lldb::addr_t getRemoteAddressForLocal(lldb::addr_t localAddress);

  /// Look up the object in m_address_map that contains a given address, find
  /// where it was copied to, and return its address range in the target
  /// process
  AddrRange getRemoteRangeForLocal(lldb::addr_t localAddress);

  /// Commit all allocations to the process and record where they were stored.
  bool commitAllocations(lldb::ProcessSP &process);

  /// Commit a single allocation to the process and record where it was stored.
  bool commitOneAllocation(lldb::ProcessSP &process,
                           lldb_private::Status &error,
                           AllocationRecord &record);

  /// Report all committed allocations to the execution engine.
  void reportAllocations(llvm::ExecutionEngine &engine);

  /// Write the contents of all allocations to the process.
  bool writeData(lldb::ProcessSP &process);

  //===--------------------------------------------------------------------===//
  // Fields
  //===--------------------------------------------------------------------===//

  struct Impl;
  class MemoryManager;

  std::unique_ptr<Impl> impl;
};

} // namespace M::KGEN::Mojo

#endif // KGEN_LIB_MOJOLLDB_EXPRESSIONPARSER_JITEXECUTIONUNIT_H
