load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "_interpreter_ops",
    srcs = glob(["**/*.py"]),
    deps = [
        "//max/python/max:_core",
        "//max/python/max:_eager_policy",
        "//max/python/max:_mlir_context",
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/engine",
        "//max/python/max/experimental",
        "//max/python/max/graph",
        "//max/python/max/mlir",
        requirement("numpy"),
    ],
)
