load("//bazel:api.bzl", "lit_tests", "mojo_filecheck_test", "mojo_test")

package(default_visibility = ["//visibility:private"])

_FILECHECK_TESTS = [
    "test_trap.mojo",
    "test_process.mojo",
]

_GPU_FILECHECK_TESTS = [
    "test_trap_gpu.mojo",
]

_LIT_TESTS = [
    "test_no_trap.mojo",
    "path/test_islink.mojo",
]

_ENV = {
    "test_env.mojo": {"TEST_MYVAR": "MyValue"},
}

_EXPECT_CRASH = [
    "test_trap.mojo",
    "test_trap_gpu.mojo",
]

[
    mojo_filecheck_test(
        name = src + ".test",
        srcs = [src],
        copts = [
            "--debug-level",
            "full",
        ],
        expect_crash = src in _EXPECT_CRASH,
        deps = [
            "@mojo//:std",
            "@mojo//:test_utils",
        ],
    )
    for src in _FILECHECK_TESTS
]

_EXTRA_CONSTRAINTS = {
    "test_trap_gpu.mojo": select({
        "//:apple_gpu": ["@platforms//:incompatible"],  # FIXME: MOCO-3697
        "//:amd_gpu": ["@platforms//:incompatible"],  # FIXME: MSTDL-2696 / ROCm/ROCm#6245 - ROCm aborts on GPU trap flakily
        "//conditions:default": [],
    }),
}

[
    mojo_filecheck_test(
        name = src + ".test",
        srcs = [src],
        copts = [
            "--debug-level",
            "full",
        ],
        expect_crash = src in _EXPECT_CRASH,
        tags = ["gpu"],
        target_compatible_with = ["//:has_gpu"] + _EXTRA_CONSTRAINTS.get(src, []),
        deps = [
            "//max:max_mojo",
            "@mojo//:std",
            "@mojo//:test_utils",
        ],
    )
    for src in _GPU_FILECHECK_TESTS
]

[
    mojo_test(
        name = src + ".test",
        srcs = [src],
        copts = [
            "--debug-level",
            "full",
        ],
        data = [src],  # NOTE: some tests attempt to read their source files
        env = _ENV.get(src, {}),
        target_compatible_with = [],
        deps = [
            "@mojo//:std",
            "@mojo//:test_utils",
        ],
    )
    for src in glob(
        ["**/*.mojo"],
        exclude = _FILECHECK_TESTS + _GPU_FILECHECK_TESTS + _LIT_TESTS,
    )
]

lit_tests(
    name = "lit_tests",
    size = "large",
    srcs = _LIT_TESTS,
    mojo_deps = [
        "@mojo//:std",
    ],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
