//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

#include "Support.h"
#include "gtest/gtest.h"

using namespace M;
using namespace lldb;
using namespace ::testing::internal;

TEST(PrimitiveTypesTest, testBool) {
  // There's no SB API for getting the bit size of a type, but the byte size
  // should be 1.

  StopContext ctx = buildAndLaunch("bool.mojo");
  SBValue trueVar = ctx.frame.FindVariable("true");
  EXPECT_STREQ(trueVar.GetTypeName(), "!kgen.scalar<bool>");
  EXPECT_EQ((int)trueVar.GetByteSize(), 1);
  EXPECT_EQ((int)trueVar.GetChildAtIndex(0).GetValueAsUnsigned(2), 1);
  EXPECT_STREQ(trueVar.GetSummary(), "True");

  SBValue falseVar = ctx.frame.FindVariable("false");
  EXPECT_STREQ(falseVar.GetTypeName(), "!kgen.scalar<bool>");
  EXPECT_EQ((int)falseVar.GetByteSize(), 1);
  EXPECT_EQ((int)falseVar.GetChildAtIndex(0).GetValueAsUnsigned(2), 0);
  EXPECT_STREQ(falseVar.GetSummary(), "False");

  SBValue otherVar = ctx.frame.FindVariable("other");
  EXPECT_STREQ(otherVar.GetTypeName(), "!kgen.scalar<bool>");
  EXPECT_EQ((int)otherVar.GetByteSize(), 1);
  EXPECT_EQ((int)otherVar.GetChildAtIndex(0).GetValueAsUnsigned(2), 1);
  EXPECT_STREQ(otherVar.GetSummary(), "True");
}

TEST(PrimitiveTypesTest, testInvalidScalar) {
  /// Ensures that `scalar<invalid>` is correctly considered as having 0
  /// bytes. It also expects to have an inner data type of `None`.
  /// A very common case where this is found is `Dict`, so we start with a
  /// `Dict` variable and navigate its members until reaching the invalid value.

  StopContext ctx = buildAndLaunch("invalid.mojo");
  SBValue a = ctx.frame.FindVariable("a");
  SBValue x = a.GetChildMemberWithName("x");
  EXPECT_STREQ(x.GetTypeName(), "!kgen.pointer<scalar<invalid>>");
  SBValue invalid = x.GetChildAtIndex(0);
  EXPECT_STREQ(invalid.GetTypeName(), "!kgen.none");
  EXPECT_EQ((int)invalid.GetByteSize(), 0);
}

TEST(PrimitiveTypesTest, testPointerChild) {
  /// Ensures that the child of a pointer type is correctly generated by
  /// the typesystem and has a valid name.
  /// There are two ways to access the pointee type: GetChildAtIndex(0) and
  /// Dereference(). They are equivalent.

  StopContext ctx = buildAndLaunch("pointer.mojo");
  SBValue var = ctx.frame.FindVariable("int_pointer");
  SBValue child = var.GetChildAtIndex(0);
  EXPECT_STREQ(var.Dereference().GetName(), "*int_pointer");
  EXPECT_STREQ(child.GetName(), "[0]"); // TODO: this might be wrong
  EXPECT_STREQ(child.GetValue(), "101");
  EXPECT_STREQ(var.Dereference().GetChildAtIndex(0).GetValue(), "101");
}

TEST(PrimitiveTypesTest, testInvalidPointer) {
  /// Ensures that the a DType.invalid pointer is correctly parsed.

  StopContext ctx = buildAndLaunch("invalid_pointer.mojo");
  SBValue var = ctx.frame.FindVariable("ptr");
  EXPECT_STREQ(var.GetTypeName(), "!kgen.pointer<scalar<invalid>>");
}

static void checkIntPair(SBValue &strct, int fst, int snd) {
  EXPECT_STREQ(strct.GetDisplayTypeName(), "MyPair");
  ASSERT_EQ((int)strct.GetNumChildren(), 2);
  SBValue firstField = strct.GetChildAtIndex(0).GetChildAtIndex(0);
  EXPECT_EQ((int)firstField.GetValueAsSigned(fst - 1), fst);
  SBValue secondField = strct.GetChildAtIndex(1).GetChildAtIndex(0);
  EXPECT_EQ((int)secondField.GetValueAsSigned(snd - 1), snd);
}

TEST(PrimitiveTypesTest, testStructAccess) {
  /// Ensures that the a DType.invalid pointer is correctly parsed.

  StopContext ctx = buildAndLaunch("struct_access.mojo");
  SBValue p = ctx.frame.FindVariable("p");
  checkIntPair(p, 1, 2);

  ctx.resume();
  p = ctx.frame.FindVariable("p");
  //  checkIntPair(p, 3, 4);

  ctx.resume();
  SBValue pp = ctx.frame.FindVariable("pp");
  EXPECT_STREQ(pp.GetDisplayTypeName(), "MyPairPair");
  ASSERT_EQ((int)pp.GetNumChildren(), 2);
  SBValue ppFirst = pp.GetChildAtIndex(0);
  checkIntPair(ppFirst, 5, 6);
  SBValue ppSecond = pp.GetChildAtIndex(1);
  checkIntPair(ppSecond, 7, 8);
}

TEST(PrimitiveTypesTest, testStructFieldOffset) {
  /// Make sure struct field offset calculation is correct by accessing struct
  /// members.

  StopContext ctx = buildAndLaunch("struct_field_offset.mojo");
  SBValue strct = ctx.frame.FindVariable("p");
  ASSERT_EQ((int)strct.GetNumChildren(), 2);
  SBValue first = strct.GetChildAtIndex(0);
  EXPECT_EQ((int)first.GetChildAtIndex(0).GetValueAsSigned(-1), 42);
  SBValue second = strct.GetChildAtIndex(1);
  EXPECT_EQ(second.GetChildAtIndex(0).GetValueAsSigned(-1), 3735928559);
}

TEST(PrimitiveTypesTest, testRecursiveStruct) {
  StopContext ctx = buildAndLaunch("recursive_struct.mojo");

  SBValue strct = ctx.frame.FindVariable("f2");
  ASSERT_EQ((int)strct.GetNumChildren(), 2);
  SBValue second = strct.GetChildAtIndex(1);
  EXPECT_STREQ(second.GetTypeName(), "!kgen.pointer<none>");

  SBValue strct2 = ctx.frame.FindVariable("b2");
  ASSERT_EQ((int)strct2.GetNumChildren(), 2);
  SBValue second2 = strct2.GetChildAtIndex(1);
  EXPECT_STREQ(second2.GetTypeName(), "!kgen.pointer<none>");
}

TEST(PrimitiveTypesTest, testTupleAndSIMD) {
  // Test that we can parse a StaticTuple and a SIMD with similar entries.
  // In DWARF, they are both array types but SIMD is marked as vector, which
  // means that the layout is different.

  StopContext ctx = buildAndLaunch("static_tuple.mojo");
  CommandResult result = ctx.runCommand("v");

  // With the scalar summary provider, array elements show their value directly,
  // causing LLDB to use a one-liner format for the array.
  EXPECT_TRUE(StringRef(result.output)
                  .contains("__mlir_type.`!pop.array<4, scalar<si16>>`"));
  EXPECT_TRUE(StringRef(result.output)
                  .contains("tuple = ([0] = 1, [1] = 2, [2] = 3, [3] = 4)"));
  EXPECT_TRUE(
      StringRef(result.output).contains("__mlir_type.`!kgen.simd<4, si16>`"));
  EXPECT_TRUE(StringRef(result.output)
                  .contains("simd = ([0] = 1, [1] = 2, [2] = 3, [3] = 4)"));
}

TEST(PrimitiveTypesTest, testPointerToClosure) {
  StopContext ctx = buildAndLaunch("pointer_to_closure.mojo");
  SBValue callback =
      ctx.frame.FindVariable("self").GetChildMemberWithName("callback");
  EXPECT_STREQ(callback.GetTypeName(),
               "!kgen.pointer<!lit.generator<() -> !kgen.none>>");
  EXPECT_NE(callback.GetValueAsAddress(), (lldb::addr_t)0);
}

TEST(PrimitiveTypesTest, testBuiltinTypes) {
  StopContext ctx = buildAndLaunch("builtin_types.mojo");
  EXPECT_EQ(ctx.runCommand("v none").output, "(None) none = None\n");
  EXPECT_EQ(ctx.runCommand("v a_var_index").output,
            "(__mlir_type.index) a_var_index = 48\n");
  EXPECT_EQ(ctx.runCommand("v a_register_passable_struct").output,
            R"((ARegisterPassableStruct) a_register_passable_struct = {
  int = -101
  f32 = 24.125
  another_int = 101
  float16 = 25.125
  uint8 = 123
  simd = ([0] = -0.125, [1] = -1.5, [2] = -1, [3] = 5.7266)
  none = None
  uint16 = 123
  int32 = 485
}
)");
  EXPECT_EQ(ctx.runCommand("v a_struct").output,
            "(AStruct) a_struct = {\n"
            "  int = 12\n"
            "  tuple = ([0] = 1, [1] = 87, [2] = 123.125)\n"
            "}\n");
  EXPECT_EQ(ctx.runCommand("v p_struct_int").output,
            "(ParamStruct) p_struct_int = (t = 8)\n");
  EXPECT_TRUE(RE::PartialMatch(ctx.runCommand("v p_struct_string_slice").output,
                               R"("hello")"));
  EXPECT_EQ(ctx.runCommand("v an_int").output,
            "(__mlir_type.`!kgen.scalar<index>`) an_int = 123\n");
  EXPECT_EQ(ctx.runCommand("v a_literal_float").output,
            "(__mlir_type.`!kgen.scalar<f64>`) a_literal_float = 3.125\n");
  EXPECT_EQ(ctx.runCommand("v a_float").output,
            "(__mlir_type.`!kgen.scalar<f32>`) a_float = 3.125\n");
  EXPECT_EQ(ctx.runCommand("v another_float").output,
            "(__mlir_type.`!kgen.scalar<f32>`) another_float = 4.125\n");
  EXPECT_STREQ(
      ctx.frame.FindVariable("^ uncommon name").GetChildAtIndex(0).GetValue(),
      "1123123");
  EXPECT_EQ(ctx.runCommand("v a_string").output,
            "(String) a_string = \"fofofo\"\n");
  // FIXME(37682): Reenable list printing
  // (*index, scalar<f64>, index) a_list = {
  //   [0] = 1
  //   [1] = 2
  //   [2] = 3
  // }
  EXPECT_EQ(ctx.runCommand("v a_simd").output,
            "(__mlir_type.`!kgen.simd<4, f16>`) a_simd = ([0] = 1.125, [1] = "
            "2.5, [2] = 0, [3] = "
            "-3.7246)\n");
  EXPECT_EQ(ctx.runCommand("v b_simd --show-all-children").output,
            R"((__mlir_type.`!kgen.simd<32, si64>`) b_simd = {
  [0] = 1
  [1] = 2
  [2] = 3
  [3] = 4
  [4] = 5
  [5] = 6
  [6] = 7
  [7] = 8
  [8] = 9
  [9] = 10
  [10] = 11
  [11] = 12
  [12] = 13
  [13] = 14
  [14] = 15
  [15] = 16
  [16] = -1
  [17] = -2
  [18] = -3
  [19] = -4
  [20] = -5
  [21] = -6
  [22] = -7
  [23] = -8
  [24] = -9
  [25] = -10
  [26] = -11
  [27] = -12
  [28] = -13
  [29] = -14
  [30] = -15
  [31] = -16
}
)");
  EXPECT_EQ(
      ctx.runCommand("v c_simd").output,
      "(__mlir_type.`!kgen.simd<2, index>`) c_simd = ([0] = 5, [1] = 6)\n");
  // Unsigned types must display as unsigned decimal (not signed). Without the
  // GetFormat fix these would show as -1 instead of their true unsigned values.
  EXPECT_EQ(ctx.runCommand("v u8_max").output,
            "(__mlir_type.`!kgen.scalar<ui8>`) u8_max = 255\n");
  EXPECT_EQ(ctx.runCommand("v u64_max").output,
            "(__mlir_type.`!kgen.scalar<ui64>`) u64_max = "
            "18446744073709551615\n");
}

TEST(PrimitiveTypesTest, testScalarMembers) {
  // Test that struct members typed as SIMD[T, 1] (Scalar[T]) display
  // correctly.  This exercises the !kgen.simd<1, ...> fallback in
  // unwrapToScalarOrPointer, which is critical for the upcoming Int = SIMD[1]
  // unification.

  StopContext ctx = buildAndLaunch("scalar_members.mojo");
  CommandResult result = ctx.runCommand("v s");
  // The struct should display with readable scalar values, not "Summary
  // Unavailable".  Check that the field names and values are present.
  EXPECT_TRUE(StringRef(result.output).contains("int_scalar"));
  EXPECT_TRUE(StringRef(result.output).contains("42"));
  EXPECT_TRUE(StringRef(result.output).contains("bool_scalar"));
  EXPECT_TRUE(StringRef(result.output).contains("uint8_scalar"));
  EXPECT_TRUE(StringRef(result.output).contains("255"));
}
