# Qwen2.5VL integration tests.

load(
    "//bazel:api.bzl",
    "modular_py_library",
    "modular_py_test",
    "requirement",
)

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

filegroup(
    name = "qwen2_5vl_3b_config",
    srcs = ["configs/qwen2_5vl_3b/config.json"],
)

modular_py_test(
    name = "test_preprocess_cache",
    srcs = ["test_preprocess_cache.py"],
    deps = [
        "//max/python/max/pipelines/architectures/qwen2_5vl",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/support",
        requirement("numpy"),
        requirement("pillow"),
    ],
)

modular_py_test(
    name = "test_image_processor",
    srcs = ["test_image_processor.py"],
    tags = [
        "manual",
        "requires-network",
    ],
    deps = [
        "//max/python/max/pipelines/architectures/qwen2_5vl",
        requirement("numpy"),
        requirement("pillow"),
        requirement("transformers"),
    ],
)

modular_py_test(
    name = "qwen2_5vl",
    size = "enormous",
    srcs = glob(
        [
            "tests/test_*.py",
            "utils/*.py",
        ],
    ) + ["tests/__init__.py"],
    data = [":qwen2_5vl_3b_config"],
    env = {
        "MODULAR_TORCH_MEMORY_PERCENT": "0.5",
    },
    exec_properties = {
        "test.resources:gpu-memory": "3",
    },
    gpu_constraints = ["//:has_gpu"] + select({
        "//:apple_gpu": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),  # FIXME: MOCO-2411
    ignore_extra_deps = [
        requirement("torchvision"),  # needed by qwenvl_utils
    ],
    imports = ["."],
    tags = [
        "gpu",
        "manual",
        "requires-network",
    ],
    deps = [
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/engine",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/qwen2_5vl",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        requirement("numpy"),
        requirement("pillow"),
        requirement("pytest-asyncio"),
        requirement("pytest-mock"),
        requirement("torch"),
        requirement("torchvision"),  # needed by qwenvl_utils
        requirement("transformers"),
        requirement("qwen-vl-utils"),
        requirement("opencv-python"),
    ],
)

modular_py_test(
    name = "test_vision_functions",
    srcs = ["test_vision_functions.py"],
    target_compatible_with = select({
        "@platforms//os:macos": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),  # FIXME: MOCO-2411
    deps = [
        "//max/python/max/pipelines/architectures/qwen2_5vl",
        requirement("torch"),
        requirement("numpy"),
        requirement("transformers"),
    ],
)

modular_py_library(
    name = "generate_utils",
    testonly = True,
    srcs = ["generate_utils.py"],
    imports = [".."],
    tags = ["no-pydeps"],  # TODO: Fix and re-enable
    deps = [
        "//max/tests/integration/test_common:storage",
        "//max/tests/integration/test_common:test_data",
        "//max/tests/integration/test_common:torch_utils",
        requirement("numpy"),
        requirement("pillow"),
        requirement("requests"),
        requirement("torch"),
        requirement("torchvision"),
        requirement("transformers"),
        requirement("qwen-vl-utils"),  # Used by qwen2.5-vl.
    ],
)

modular_py_test(
    name = "test_config_init",
    srcs = ["test_config_init.py"],
    data = [":qwen2_5vl_3b_config"],
    deps = [
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/qwen2_5vl",
        "//max/python/max/pipelines/lib",
        requirement("transformers"),
    ],
)

modular_py_test(
    name = "test_compute_multimodal_merge_indices",
    size = "large",
    srcs = ["test_compute_multimodal_merge_indices.py"],
    deps = [
        "//max/python/max/pipelines/architectures/qwen2_5vl",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        requirement("numpy"),
    ],
)
