load("//bazel:api.bzl", "modular_py_binary", "modular_py_library", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_library(
    name = "logit_verification_config",
    srcs = ["logit_verification_config.py"],
    data = ["logit_verification_config.yaml"],
    visibility = [
        "//:__pkg__",
        "//SDK/integration-test:__subpackages__",
        "//ci/verify_pipelines:__pkg__",
        "//max/tests:__subpackages__",
        "//oss/modular/max/tests:__subpackages__",
    ],
    deps = [
        requirement("pydantic"),
        requirement("pyyaml"),
    ],
)

modular_py_binary(
    name = "make_goldens_bazel_accessible",
    srcs = ["make_goldens_bazel_accessible.py"],
    deps = [
        ":logit_verification_config",
    ],
)

modular_py_test(
    name = "test_logit_verification_config",
    size = "medium",
    srcs = ["test_logit_verification_config.py"],
    deps = [
        ":logit_verification_config",
    ],
)
