load("//bazel:api.bzl", "modular_run_binary_test", "mojo_binary")

package(default_visibility = ["//visibility:private"])

mojo_binary(
    name = "tile_tensor_examples",
    srcs = ["tile_tensor_examples.mojo"],
    deps = [
        "//max:layout",
        "@mojo//:std",
    ],
)

modular_run_binary_test(
    name = "tile_tensor_examples_test",
    binary = "tile_tensor_examples",
)

GPU_TEST_SRCS = [
    "tile_tensor_gpu_examples.mojo",
    "tile_tensor_init_from_cpu.mojo",
    "tile_tensor_tile_copier.mojo",
]

[
    mojo_binary(
        name = src.split(".")[0],
        srcs = [src],
        target_compatible_with = ["//:has_gpu"],
        deps = [
            "//max:layout",
            "@mojo//:std",
        ],
    )
    for src in GPU_TEST_SRCS
]

[
    modular_run_binary_test(
        name = src.split(".")[0] + "_test",
        size = "small",
        binary = src.split(".")[0],
    )
    for src in GPU_TEST_SRCS
]
