[workspace]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Examples of using TileTensors"
name = "TileTensor examples"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
max = "*"

[tasks]
tile_tensor = "mojo run tile_tensor_examples.mojo"
tile_tensor_gpu = "mojo run tile_tensor_gpu_examples.mojo"
tile_tensor_all = "mojo run tile_tensor_examples.mojo && mojo run tile_tensor_gpu_examples.mojo"
