// RUN: kgen-opt %s -elaborate-generators="use-parametric-interpret=false" -lower-kgen-to-llvm | FileCheck %s
// RUN: kgen-opt %s -elaborate-generators="use-parametric-interpret=true" -lower-kgen-to-llvm | FileCheck %s

// COM: This file specifically tests that the interpretation of
// COM: `pop.string.address` matches the address generated by the lowering.

kgen.generator @string_address<astr: !kgen.string>() -> !kgen.pointer<scalar<si8>> {
  //  kgen.param.declare concat_str: string = <str_concat("hello ", "world")>
  %0 = kgen.param.constant: !kgen.pointer<scalar<si8>> = <string_address(:!kgen.string astr)>
  kgen.return %0 : !kgen.pointer<scalar<si8>>
}


// CHECK-LABEL: llvm.func @check_string_table
kgen.generator export @check_string_table() -> (!kgen.pointer<scalar<si8>>, !kgen.string) {
  kgen.param.declare value: string = <"hello">
  // CHECK: llvm.mlir.addressof @[[STATIC_STRING:.*]] :
  %0 = kgen.param.constant: !kgen.pointer<scalar<si8>> = <apply(
    :() -> !kgen.pointer<scalar<si8>> @string_address<:!kgen.string value>)>
  // CHECK: llvm.mlir.addressof @[[STATIC_STRING]] :
  %1 = kgen.param.constant: string = <value>
  kgen.return %0, %1 : !kgen.pointer<scalar<si8>>, !kgen.string
}

kgen.generator @string_address2(%arg0: !kgen.string) -> !kgen.pointer<scalar<si8>> {
  %0 = pop.string.address %arg0
  kgen.return %0 : !kgen.pointer<scalar<si8>>
}

// CHECK-LABEL: llvm.func @check_string_table2
kgen.generator export @check_string_table2() -> (!kgen.pointer<scalar<si8>>, !kgen.string) {
  kgen.param.declare value: string = <"hello">
  // CHECK: llvm.mlir.addressof @[[STATIC_STRING:.*]] :
  %0 = kgen.param.constant: !kgen.pointer<scalar<si8>> = <apply(
    :(!kgen.string) -> !kgen.pointer<scalar<si8>> @string_address2, value)>
  // CHECK: llvm.mlir.addressof @[[STATIC_STRING]] :
  %1 = kgen.param.constant: string = <value>
  kgen.return %0, %1 : !kgen.pointer<scalar<si8>>, !kgen.string
}


// CHECK: llvm.mlir.global internal constant @[[STATIC_STRING]]("hello\00")
// CHECK-NOT: llvm.mlir.global
