load("//bazel:api.bzl", "modular_py_library")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "eagle_common",
    srcs = glob(["**/*.py"]),
    test_docstring_examples = True,
    deps = [
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/deepseekV3",
    ],
)
