load("//bazel:api.bzl", "mojo_library")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS")

package(default_visibility = ["//max:consumers"])

mojo_library(
    name = "builtin_primitives",
    srcs = glob(["**/*.mojo"]),
    docs_base_path = "kernels",
    ignore_deprecated = IGNORED_POINTER_DEPRECATIONS,
    use_production_compiler_for_asan = True,
    validate_missing_docs = False,
    deps = [
        "//max:extensibility",
        "//max:layout",
        "//max:max_mojo",
        "//max:nn",
        "@mojo//:std",
    ],
)
