load("//bazel:api.bzl", "mojo_test")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS_COPTS")

package(default_visibility = ["//max:consumers"])

_UTILS = ["conv_utils.mojo"]

_CPU_ONLY = [
    "fig19_3.mojo",
    "fig19_4.mojo",
]

[
    mojo_test(
        name = src.removesuffix(".mojo") + ".test",
        size = "medium",
        srcs = [src] + _UTILS,
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        main = src,
        tags = ["gpu"],
        target_compatible_with = ["//:has_gpu"],
        deps = [
            "//max:max_mojo",
            "@mojo//:std",
        ],
    )
    for src in glob(
        ["*.mojo"],
        exclude = _UTILS + _CPU_ONLY,
    )
]

[
    mojo_test(
        name = src.removesuffix(".mojo") + ".test",
        size = "small",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        deps = [
            "@mojo//:std",
        ],
    )
    for src in _CPU_ONLY
]
