load("//bazel:api.bzl", "mojo_test")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS_COPTS")

package(default_visibility = ["//max:consumers"])

# All SM100 tests require B200 GPU
[
    mojo_test(
        name = src + ".test",
        size = "large",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        enable_assertions = True,
        exec_properties = {
            "test.resources:gpu-memory": "3",
        },
        tags = ["gpu"],
        target_compatible_with = [
            "//:has_gpu",
            "//:b200_gpu",
        ],
        deps = [
            "//max:internal_utils",
            "//max:linalg",
            "//max:max_mojo",
            "//max:structured_kernels",
            "@mojo//:std",
            "@mojo//:test_utils",
        ],
    )
    for src in glob(["*.mojo"])
]
