# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

from std.math import exp2
from std.pathlib import Path
from std.sys._assembly import inlined_assembly

from max.gpu import thread_idx
from max.gpu.sync import barrier
from max.gpu.host import DeviceContext
from max.gpu.host.compile import _compile_code
from max.gpu.host.info import A100
from std.memory import unsafe_stack_allocation


def kernel(x: Int) -> Int:
    return thread_idx.x


def parametric[f: def(Int) thin -> Int]() -> Int:
    return f(42)


# CHECK-LABEL: test_compile_code
def test_compile_code() raises:
    print("== test_compile_code")

    # CHECK: Generated by LLVM NVPTX Back-End
    # CHECK: .visible .entry  test_compile_nvptx_kernel_
    print(_compile_code[kernel]())
    # CHECK: Generated by LLVM NVPTX Back-End
    # CHECK: .visible .entry test_compile_nvptx_parametric_
    print(_compile_code[parametric[kernel]]())
    # CHECK: ; ModuleID =
    # CHECK: lvm.nvvm.read.ptx.sreg.tid.x()
    print(_compile_code[parametric[kernel], emission_kind="llvm"]())


# CHECK-LABEL: test_compile_function
def test_compile_function() raises:
    print("== test_compile_function")

    def kernel(x: MutPointer[Int, MutAnyOrigin]):
        x[0] = thread_idx.x

    # CHECK: tid.x

    with DeviceContext() as ctx:
        _ = ctx.compile_function[kernel, dump_asm=True]()


def kernel_inlined_assembly():
    inlined_assembly["nanosleep.u32 $0;", NoneType, constraints="r"](
        UInt32(100)
    )


# CHECK-LABEL: test_compile_function_with_assembly
def test_compile_function_with_assembly() raises:
    print("== test_compile_function_with_assembly")

    # CHECK: nanosleep
    # CHECK-NOT: begin assembly

    with DeviceContext() as ctx:
        _ = ctx.compile_function[kernel_inlined_assembly, dump_asm=True]()


# CHECK-LABEL: test_compile_function_with_path
def test_compile_function_with_path() raises:
    print("== test_compile_function_with_path")

    # CHECK: nanosleep
    # CHECK-NOT: begin assembly

    with DeviceContext() as ctx:
        comptime out_file = Path("/tmp/my_file.ptx")
        _ = ctx.compile_function[kernel_inlined_assembly, dump_asm=out_file]()
        print(out_file.read_text())


# CHECK-LABEL: test_compile_function_with_path_func
def test_compile_function_with_path_func() raises:
    print("== test_compile_function_with_path_func")

    # CHECK: nanosleep
    # CHECK-NOT: begin assembly

    with DeviceContext() as ctx:
        var out_file_name = "my_file_2.ptx"
        comptime out_dir = Path("/tmp")

        @__parameter
        def dummy_fn() capturing -> Path:
            return out_dir / out_file_name

        _ = ctx.compile_function[kernel_inlined_assembly, dump_asm=dummy_fn]()

        var out_file = out_dir / out_file_name
        print(out_file.read_text())


# CHECK-LABEL: test_short_nvptx_ptr
def test_short_nvptx_ptr() raises:
    print("== test_short_nvptx_ptr")

    def do_some_shared_mem_op(src: ImmPointer[Int32, ImmutAnyOrigin]):
        var a = unsafe_stack_allocation[20, Int32, address_space=.SHARED]()
        a[thread_idx.x] = src[0]
        barrier()

    # CHECK: // demoted variable
    # CHECK-NOT: mov.u64
    # CHECK: mov.u32
    # CHECK-NEXT: shl.b32
    # CHECK-NEXT: mov.b32
    # CHECK-NEXT: add.s32
    # CHECK-NEXT: ld.global.b32
    # CHECK-NEXT: st.shared.b32
    with DeviceContext() as ctx:
        _ = ctx.compile_function[do_some_shared_mem_op, dump_asm=True]()


# CHECK-LABEL: test_exp2_compile
def test_exp2_compile() raises:
    print("== test_exp2_compile")

    # https://godbolt.org/z/j9ecfjjP1
    def exp_op(output: MutPointer[Float32, MutAnyOrigin], max_scaled: Int32):
        output[] = exp2(
            output[] * 1.44269504088896340736 - max_scaled.cast[.float32]()
        )

    # CHECK: "target-cpu"="sm_80" "target-features"="+ptx81,+sm_80" "tune-cpu"="sm_80"
    print(
        _compile_code[exp_op, target=A100.target(), emission_kind="llvm-opt"]()
    )
    # CHECK: fma.rn.f32
    print(_compile_code[exp_op, target=A100.target(), emission_kind="asm"]())

    # CHECK: fma.rn.ftz.f32
    print(
        _compile_code[
            exp_op,
            target=A100.target(),
            emission_kind="asm",
            compile_options="target-abi=shortptr,denormal-fp-math-f32=preserve-sign",
        ]()
    )


def main() raises:
    test_compile_code()
    test_compile_function()
    test_compile_function_with_assembly()
    test_compile_function_with_path()
    test_compile_function_with_path_func()
    test_short_nvptx_ptr()
    test_exp2_compile()
