# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
"""Request and response types for cascade generative-AI pipelines.

One interface covers every modality. A pipeline declares which modalities it
accepts and produces, takes a :class:`GenAIRequest`, and streams
:data:`GenAIChunk` values that are *already structured* -- assistant text,
reasoning, tool calls, and images are distinct chunk types rather than regions a
consumer has to recover from a flat character stream. Splitting a model's raw
output into those regions is the pipeline's job, because the pipeline is what
knows the model's format; the serving layer only maps chunks onto the schema its
route speaks.

The same chunk types double as message content, so a conversation turn and a
generated response share one vocabulary: a prior assistant turn's tool call is a
:class:`GenAIToolCall`, an input image is a :class:`GenAIImageChunk`. The only
difference is completeness -- in a message every chunk is whole, while in a
stream successive chunks are fragments to concatenate (see :class:`GenAIToolCall`
for the one case where that distinction needs care).

Kept in ``interfaces`` (below both ``workers`` and the concrete ``pipelines``)
so workers can consume the request types and ``serve`` can route on the
interface without either depending on concrete pipeline implementations.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncIterable, AsyncIterator
from enum import Enum
from typing import Annotated, Literal, TypeAlias, Union

from max.experimental.cascade.core import pipeline_method
from pydantic import BaseModel, ConfigDict, Field, model_validator


class Modality(str, Enum):
    """A kind of content a pipeline can consume or produce."""

    TEXT = "text"
    IMAGE = "image"


# --- content chunks -------------------------------------------------------
#
# Every chunk carries a literal ``type`` tag. The tag is what makes the union
# discriminable, which matters because chunks cross worker process boundaries as
# JSON and are rebuilt by ``TypeAdapter(GenAIChunk).validate_json(...)``.


class GenAITextChunk(BaseModel):
    """Assistant-visible text."""

    type: Literal["text"] = "text"

    text: str
    """The text itself. A fragment when streamed, the whole run in a message."""


class GenAIReasoningChunk(BaseModel):
    """Model chain-of-thought, kept separate from assistant-visible text.

    Reasoning models wrap their thinking in delimiters that the pipeline strips;
    what reaches here is the thinking text alone, never the markers.
    """

    type: Literal["reasoning"] = "reasoning"

    text: str
    """The reasoning text. A fragment when streamed, the whole run in a message."""


class GenAIToolCall(BaseModel):
    """A request from the model to invoke a tool.

    Streaming a tool call is not the same as streaming text: arguments arrive as
    a JSON fragment at a time and only the first chunk of a given call carries
    its ``id`` and ``name``. ``index`` is what ties the fragments together --
    consecutive chunks sharing an index are one call, and their ``arguments``
    concatenate into the final JSON object.

    In a message (a prior assistant turn being replayed as history) a tool call
    is complete: ``id``, ``name``, and the full ``arguments`` JSON are all set.
    """

    type: Literal["tool_call"] = "tool_call"

    index: int = 0
    """Position of this call in the response, and the key that groups fragments."""

    id: str | None = None
    """Unique call id. Set on the first fragment of a call, ``None`` after."""

    name: str | None = None
    """Tool being invoked. Set on the first fragment of a call, ``None`` after."""

    arguments: str | None = None
    """Arguments as JSON. A fragment when streamed, the whole object in a message."""


class GenAIImageChunk(BaseModel):
    """An image, either generated by the model or supplied with a prompt.

    Generated images always arrive as ``data``. An image supplied by a client may
    arrive either way, since chat APIs accept both inline data URIs and remote
    URLs; a pipeline that cannot fetch a URL should reject ``url`` inputs rather
    than silently ignoring them.
    """

    # Base64 in JSON, raw bytes in Python. The codec's raw-binary slot only
    # applies to a top-level ``bytes`` value, so image bytes nested in a chunk
    # would otherwise be handed to a UTF-8 JSON encoder that cannot represent
    # them.
    model_config = ConfigDict(ser_json_bytes="base64", val_json_bytes="base64")

    type: Literal["image"] = "image"

    format: str = "PNG"
    """Image encoding (``"PNG"``, ``"JPEG"``, ...)."""

    data: bytes | None = None
    """Raw image bytes."""

    url: str | None = None
    """Location of the image, when it was passed by reference rather than value."""

    @model_validator(mode="after")
    def _exactly_one_source(self) -> GenAIImageChunk:
        if (self.data is None) == (self.url is None):
            raise ValueError("GenAIImageChunk needs exactly one of data or url")
        return self


GenAIChunk: TypeAlias = Annotated[
    Union[  # noqa: UP007
        GenAITextChunk,
        GenAIReasoningChunk,
        GenAIToolCall,
        GenAIImageChunk,
    ],
    Field(discriminator="type"),
]
"""One increment of generated content, or one part of a message."""


# --- requests -------------------------------------------------------------


class ChatMessage(BaseModel):
    """One turn of a conversation."""

    role: str
    """Speaker: ``"system"``, ``"user"``, ``"assistant"``, or ``"tool"``."""

    content: list[GenAIChunk] = Field(default_factory=list)
    """The turn's content parts, in order."""

    tool_call_id: str | None = None
    """For a ``"tool"`` turn, the id of the call this message answers."""

    @classmethod
    def text(cls, role: str, text: str) -> ChatMessage:
        """Build a single-part text message, the overwhelmingly common case."""
        return cls(role=role, content=[GenAITextChunk(text=text)])


class GenAITool(BaseModel):
    """A tool the model may call, described independently of any wire format."""

    name: str

    description: str | None = None

    parameters: dict[str, object] | None = None
    """JSON Schema for the tool's arguments.

    Parsers for models whose tool grammar loses argument types (bare-text XML,
    say) use this to re-type scalars, and schema-driven streaming parsers use it
    to emit typed argument bytes.
    """


class TextGenOptions(BaseModel):
    """Generation parameters for the text output of a single request.

    Mirrors the request-configurable sampling fields that MAX Serve accepts on
    its OpenAI text-generation routes, so a route adapter can forward everything
    a client sends straight through to the model worker. Every field except
    ``num_tokens``, ``min_new_tokens`` and ``ignore_eos`` defaults to ``None``
    meaning "use the model / server default", matching how
    ``SamplingParamsInput`` is layered on top of a model's ``GenerationConfig``.
    """

    # Generation-length control.
    num_tokens: int = 10
    """Maximum number of new tokens to generate (maps to ``max_new_tokens``)."""

    min_new_tokens: int = 0
    """Minimum number of new tokens to generate before stopping."""

    ignore_eos: bool = False
    """If ``True``, keep generating past the EOS token until the token budget
    (or a stop condition) is hit."""

    # Core sampling controls.
    temperature: float = 1.0
    """Sampling temperature. Set to ``0.0`` for greedy (deterministic) decoding."""

    top_k: int | None = None
    """Keep only the ``top_k`` most probable tokens when sampling."""

    top_p: float | None = None
    """Nucleus-sampling cumulative-probability threshold."""

    min_p: float | None = None
    """Minimum token probability relative to the most likely token."""

    thinking_temperature: float | None = None
    """Temperature override for tokens inside a reasoning region."""

    seed: int | None = None
    """Random seed for reproducible sampling. ``None`` picks a random seed."""

    # Penalties.
    frequency_penalty: float | None = None
    """Penalty applied proportionally to a token's frequency so far."""

    presence_penalty: float | None = None
    """Flat penalty applied to tokens that have already appeared."""

    repetition_penalty: float | None = None
    """Factor by which logits of repeated tokens are divided."""

    # Stopping criteria.
    stop: list[str] | None = None
    """Strings that terminate generation when produced."""

    stop_token_ids: list[int] | None = None
    """Token ids that terminate generation when produced."""


class ImageGenOptions(BaseModel):
    """Generation parameters for the image output of a single request."""

    height: int = 1024
    width: int = 1024
    num_steps: int = 28
    guidance_scale: float = 3.5
    seed: int = 42
    output_format: str = "PNG"


class GenAIRequest(BaseModel):
    """A single generation request, whatever its modalities.

    Options are grouped per output modality rather than flattened, so a pipeline
    that generates both text and images reads each group independently and a
    pipeline that generates one ignores the other's defaults.
    """

    messages: list[ChatMessage] = Field(default_factory=list)

    tools: list[GenAITool] = Field(default_factory=list)
    """Tools the model may call. Empty means the model must not emit tool calls.

    A pipeline uses this to decide whether to run its tool parser at all: with no
    tools on offer, a stray marker in ordinary prose would otherwise be misread
    as a call.
    """

    tool_choice: Literal["auto", "none", "required"] = "auto"
    """Whether the model may, must not, or must call a tool."""

    text: TextGenOptions = Field(default_factory=TextGenOptions)

    image: ImageGenOptions = Field(default_factory=ImageGenOptions)

    @property
    def tools_enabled(self) -> bool:
        """Whether tool calls are possible for this request."""
        return bool(self.tools) and self.tool_choice != "none"

    def tool_schemas(self) -> dict[str, dict[str, object]]:
        """Map each offered tool's name to its parameter JSON Schema."""
        return {
            tool.name: tool.parameters
            for tool in self.tools
            if tool.parameters is not None
        }


class GenAIInterface(ABC):
    """Standard interface for a generative-AI model of any modality.

    The composable primitive is :meth:`_generate_iterator`, which returns the
    chunk stream as a worker handle. A composing pipeline can forward that handle
    to another worker so post-processing runs worker-to-worker without routing
    every chunk through the orchestrator. :meth:`generate` is the standalone
    entry point, and just wraps the handle in a pipeline scope.
    """

    @abstractmethod
    def supported_input_modalities(self) -> set[Modality]:
        """Return the modalities this pipeline accepts in request messages."""
        ...

    @abstractmethod
    def supported_output_modalities(self) -> set[Modality]:
        """Return the modalities this pipeline can emit as chunks."""
        ...

    @abstractmethod
    async def _generate_iterator(
        self, req: GenAIRequest
    ) -> AsyncIterable[GenAIChunk]:
        """Open a streaming handle to the generated chunks.

        Returns a worker stream handle rather than a materialized iterator, so a
        composing pipeline can hand it to another worker. Must be called within
        an active pipeline scope; the handle stays valid for that scope.

        Prefixed to mark it as the composition primitive: direct callers want
        :meth:`generate`, which establishes a scope of its own. The pair exists
        because :func:`~max.experimental.cascade.core.pipeline_method` scopes do
        not nest -- an inner scope shadows the outer one and would tear down the
        stream early.
        """
        ...

    @pipeline_method
    async def generate(self, req: GenAIRequest) -> AsyncIterator[GenAIChunk]:
        """Generate a streaming response to a request."""
        async for chunk in await self._generate_iterator(req):
            yield chunk
