load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//Mojo:consumers"])

modular_cc_binary(
    name = "kgen-translate",
    srcs = glob(["*.cpp"]),
    internal_deps = select({
        # Under --config=hal-device-context we don't link the full DeviceContext,
        # but we need CompilationDevice and the HAL-only CompilerDeviceArch.
        "//:hal_device_context_enabled": [
            "//MLRT:Driver/CompilationDeviceImpl",
            "//MLRT:Driver/CompilerDeviceArch",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Init",
        "//Mojo:Compiler",
        "//Mojo:CompilerRT",
        "//Mojo:ExecutionEngine",
        "//Mojo:KGENDialect",
        "//Mojo:MojoParser",
        "//Mojo:MojoTooling",
        "//Mojo:ObjectCompiler",
        "//Mojo:Pipeline",
        "//Mojo:Support",
        "//Mojo:ToolCommon",
        "//Mojo:Transforms",
        "//Support:Driver",
        "//Support:Globals",
        "//Support:MDialect",
        "@llvm-project//mlir:TranslateLib",
    ],
)
