"""Lists all of the MAX Python API subtargets"""

load("//max/python/max/pipelines/architectures:all_arches.bzl", "ALL_ARCHITECTURES")

ALL_MAX_PYTHON_DEPS = ALL_ARCHITECTURES + [
    "//max/python/max:_core",
    "//max/python/max:tensor",
    "//max/python/max/_core_mojo",
    "//max/python/max/_entrypoints",
    "//max/python/max/_entrypoints:_pipelines",
    "//max/python/max/_entrypoints:gpu-query",
    "//max/python/max/_entrypoints:pipelines",
    "//max/python/max/_entrypoints:replay_recording",
    "//max/python/max/_interpreter_ops",
    "//max/python/max/_xgrammar",
    "//max/python/max/diagnostics",
    "//max/python/max/driver",
    "//max/python/max/dtype",
    "//max/python/max/engine",
    "//max/python/max/experimental/cascade",
    "//max/python/max/experimental/cascade/deployment:context_config",
    "//max/python/max/experimental/cascade/deployment:routing",
    "//max/python/max/experimental/cascade/grpc_runtime",
    "//max/python/max/experimental/cascade/http_runtime",
    "//max/python/max/experimental/cascade/serve:main_lib",
    "//max/python/max/experimental/cascade/workers",
    "//max/python/max/experimental/nn",
    "//max/python/max/experimental/testing",
    "//max/python/max/experimental/torch",
    "//max/python/max/graph",
    "//max/python/max/kv_cache",
    "//max/python/max/mlir",
    "//max/python/max/nn",
    "//max/python/max/nn/hooks",
    "//max/python/max/pipelines",
    "//max/python/max/pipelines/architectures",
    "//max/python/max/pipelines/modeling",
    "//max/python/max/profiler",
    "//max/python/max/serve",
    "//max/python/max/serve:debug",
    "//max/python/max/serve/mocks",
    "//max/python/max/support",
]
