load("//bazel:api.bzl", "mojo_test")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS_COPTS")

package(default_visibility = ["//max:consumers"])

_CPU_ONLY = [
    "fig11_1.mojo",
]

# These examples use atomics, which are not supported on Apple GPU.
_USES_ATOMICS = [
    "fig11_17.mojo",
    "fig11_18.mojo",
]

[
    mojo_test(
        name = src.removesuffix(".mojo") + ".test",
        size = "medium",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        tags = ["gpu"],
        target_compatible_with = ["//:has_gpu"],
        deps = [
            "//max:max_mojo",
            "@mojo//:std",
        ],
    )
    for src in glob(
        ["*.mojo"],
        exclude = _CPU_ONLY + _USES_ATOMICS,
    )
]

[
    mojo_test(
        name = src.removesuffix(".mojo") + ".test",
        size = "medium",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        tags = ["gpu"],
        target_compatible_with = ["//:has_gpu"] + select({
            "//:apple_gpu": ["@platforms//:incompatible"],
            "//conditions:default": [],
        }),
        deps = [
            "//max:max_mojo",
            "@mojo//:std",
        ],
    )
    for src in _USES_ATOMICS
]

[
    mojo_test(
        name = src.removesuffix(".mojo") + ".test",
        size = "small",
        srcs = [src],
        copts = IGNORED_POINTER_DEPRECATIONS_COPTS,
        deps = [
            "@mojo//:std",
        ],
    )
    for src in _CPU_ONLY
]
