load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "profiler",
    srcs = glob(["**/*.py"]),
    test_docstring_examples = True,
    deps = [
        "//max/python/max:_core",
        requirement("msgspec"),
        requirement("psutil"),
        requirement("taskgroup"),
        requirement("typing-extensions"),
    ],
)
