load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "unified_dflash2_qwen3_5",
    srcs = glob(["**/*.py"]),
    deps = [
        requirement("transformers"),
        requirement("typing-extensions"),
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/engine",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/dflash2_qwen3_5",
        "//max/python/max/pipelines/architectures/llama3",
        "//max/python/max/pipelines/architectures/qwen3_5",
        "//max/python/max/pipelines/architectures/qwen3vl_moe",
        "//max/python/max/pipelines/architectures/unified_dflash_llama3",
        "//max/python/max/pipelines/architectures/unified_mtp_qwen3_5",
        "//max/python/max/pipelines/context",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/pipelines/speculative",
    ],
)
