//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

#ifndef DEBUGINFO_TD
#define DEBUGINFO_TD

include "Support/DebugInfoDialect/IR/DebugInfoAttrs.td"
include "Support/DebugInfoDialect/IR/DebugInfoEnums.td"
include "Support/DebugInfoDialect/IR/DebugInfoExprAttrs.td"
include "Support/DebugInfoDialect/IR/DebugInfoOps.td"
include "Support/DebugInfoDialect/IR/DebugInfoTypes.td"

#endif // DEBUGINFO_TD
