//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//
// This file is autogenerated, DO NOT EDIT
//===----------------------------------------------------------------------===//

#ifndef SUPPORT_PLATFORMLIBNAMES_H
#define SUPPORT_PLATFORMLIBNAMES_H

#include "llvm/Support/ErrorHandling.h"
#include <string>

namespace M {
struct PlatformLibrary {

  static std::string getSharedLibraryName(llvm::StringRef name);

  static std::string getStaticLibraryName(llvm::StringRef name);
};
} // namespace M

#endif // SUPPORT_PLATFORMLIBNAMES_H
