# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
"""Request types for MAX API."""

from .base import DUMMY_REQUEST_ID, Request, RequestID, RequestType
from .open_responses import (
    AllowedToolChoice,
    AssistantMessage,
    AudioGenerationDetails,
    DeveloperMessage,
    Error,
    FastAPIRequestProtocol,
    FunctionCall,
    FunctionCallOutput,
    FunctionCallStatus,
    FunctionTool,
    FunctionToolChoice,
    FunctionToolParam,
    ImageDetail,
    ImageGenerationDetails,
    IncludeEnum,
    IncompleteDetails,
    InputContent,
    InputFileContent,
    InputImageContent,
    InputMessage,
    InputTextContent,
    InputTokensDetails,
    InputVideoContent,
    ItemReferenceParam,
    JsonObjectField,
    JsonObjectParam,
    JsonSchemaField,
    JsonSchemaParam,
    LogProb,
    MediaDataUriFetcher,
    Message,
    MessageRole,
    MessageStatus,
    OpenResponsesRequest,
    OpenResponsesRequestBody,
    OutputAudioContent,
    OutputContent,
    OutputImageContent,
    OutputTextContent,
    OutputTokensDetails,
    OutputVideoContent,
    ReasoningBody,
    ReasoningEffortEnum,
    ReasoningParam,
    ReasoningReference,
    ReasoningReferenceParam,
    ReasoningSummaryContent,
    ReasoningSummaryEnum,
    RefusalContent,
    ResponseFormat,
    ResponseFormatParam,
    ResponseResource,
    ServiceTierEnum,
    StreamOptionsParam,
    SystemMessage,
    TextField,
    TextParam,
    ToolChoice,
    ToolChoiceValueEnum,
    TopLogProb,
    TruncationEnum,
    UrlCitationBody,
    UrlCitationParam,
    Usage,
    UserMessage,
    VerbosityEnum,
)

__all__ = [
    "DUMMY_REQUEST_ID",
    "AllowedToolChoice",
    "AssistantMessage",
    "AudioGenerationDetails",
    "DeveloperMessage",
    "Error",
    "FastAPIRequestProtocol",
    "FunctionCall",
    "FunctionCallOutput",
    "FunctionCallStatus",
    "FunctionTool",
    "FunctionToolChoice",
    "FunctionToolParam",
    "ImageDetail",
    "ImageGenerationDetails",
    "IncludeEnum",
    "IncompleteDetails",
    "InputContent",
    "InputFileContent",
    "InputImageContent",
    "InputMessage",
    "InputTextContent",
    "InputTokensDetails",
    "InputVideoContent",
    "ItemReferenceParam",
    "JsonObjectField",
    "JsonObjectParam",
    "JsonSchemaField",
    "JsonSchemaParam",
    "LogProb",
    "MediaDataUriFetcher",
    "Message",
    "MessageRole",
    "MessageStatus",
    "OpenResponsesRequest",
    "OpenResponsesRequestBody",
    "OutputAudioContent",
    "OutputContent",
    "OutputImageContent",
    "OutputTextContent",
    "OutputTokensDetails",
    "OutputVideoContent",
    "ReasoningBody",
    "ReasoningEffortEnum",
    "ReasoningParam",
    "ReasoningReference",
    "ReasoningReferenceParam",
    "ReasoningSummaryContent",
    "ReasoningSummaryEnum",
    "RefusalContent",
    "Request",
    "RequestID",
    "RequestType",
    "ResponseFormat",
    "ResponseFormatParam",
    "ResponseResource",
    "ServiceTierEnum",
    "StreamOptionsParam",
    "SystemMessage",
    "TextField",
    "TextParam",
    "ToolChoice",
    "ToolChoiceValueEnum",
    "TopLogProb",
    "TruncationEnum",
    "UrlCitationBody",
    "UrlCitationParam",
    "Usage",
    "UserMessage",
    "VerbosityEnum",
]
