load("//bazel:api.bzl", "mojo_test")

package(default_visibility = ["//visibility:private"])

mojo_test(
    name = "test_tracy_bridge.mojo.test",
    srcs = ["test_tracy_bridge.mojo"],
    data = [
        "//Mojo:CompilerRT",
    ],
    deps = [
        "@mojo//:std",
    ],
)

mojo_test(
    name = "test_trace_context.mojo.test",
    srcs = ["test_trace_context.mojo"],
    data = [
        "//Mojo:CompilerRT",
    ],
    deps = [
        "//max:max_mojo",
        "@mojo//:std",
    ],
)
