//===----------------------------------------------------------------------===//
// Copyright (c) 2026, Modular Inc. All rights reserved.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions:
// https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//
//
// This is the top level file for the POP dialect.
//
//===----------------------------------------------------------------------===//

#ifndef KGEN_POPDIALECT_POP_TD
#define KGEN_POPDIALECT_POP_TD

include "Mojo/POPDialect/POPAttrs.td"
include "Mojo/POPDialect/POPOps.td"
include "Mojo/POPDialect/POPTypes.td"

#endif // KGEN_POPDIALECT_POP_TD
