load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//Mojo:consumers"])

modular_cc_binary(
    name = "llvm-module-split",
    srcs = glob(["*.cpp"]),
    internal_deps = select({
        # Under --config=hal-device-context we don't link the full DeviceContext,
        # but we need CompilationDevice and the HAL-only CompilerDeviceArch.
        "//:hal_device_context_enabled": [
            "//MLRT:Driver/CompilationDeviceImpl",
            "//MLRT:Driver/CompilerDeviceArch",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//Config",
        "//Mojo:Compiler",
        "//Mojo:ObjectCompiler",
        "//Mojo:ToolCommon",
        "//Support:Base",
        "//Support:Globals",
        "@llvm-project//llvm:Support",
    ],
)
