# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Tensor filling utilities for `LayoutTensor` objects.

This module provides functions for efficiently filling tensors with various patterns
of values, including sequences and random distributions.

The module includes:
- Sequential value generation (`arange`)
- Uniform random value generation (`random`)
- Heavier-tailed (Student-t) random value generation (`randt`)
"""

from std.itertools import product
from std.math import sqrt
from std.random import random_float64
from std.random.philox import NormalRandom
from std.sys import is_nvidia_gpu
from layout.coord import Coord

from .layout import Layout
from .layout_tensor import LayoutTensor
from .tile_layout import TensorLayout
from .tile_tensor import TileTensor

from std.utils.numerics import max_finite

# A batch size for filler functions loop bounds.
comptime BATCH_SIZE = 2048


@always_inline
def _randt_sample[
    nu: Int
](mut rng: NormalRandom, amp: Float64, cap: Float64) -> Float64:
    """One Student-t sample, scaled to `amp` and clamped to `+/-cap`."""
    comptime assert not is_nvidia_gpu(), "Cannot run randt on the gpu"
    comptime assert nu >= 1 and nu <= 7, (
        "randt supports nu in [1, 7]: a sample draws nu + 1 normals and must"
        " fit ONE step_normal() vector of 8"
    )
    var z = rng.step_normal()
    var sq = z * z
    # Lane 0 is the numerator; lanes 1..nu are the chi-square terms.
    var ss = Float64(0)
    for j in range(1, nu + 1):
        ss += Float64(sq[j])
    var t = Float64(z[0]) / sqrt(ss / Float64(nu))
    return max(-cap, min(cap, t * amp))


@always_inline
def _randt_amp[nu: Int](sigma: Float64) -> Float64:
    """Divides out the theoretical sd so a fill is one pass."""
    # Var(t_nu) = nu / (nu - 2) for nu > 2 and is undefined at or below it, so
    # `sigma` degenerates to a spread parameter there rather than an sd.
    comptime pop_sd = sqrt(
        Float64(nu) / Float64(nu - 2)
    ) if nu > 2 else Float64(1)
    return sigma / pop_sd


def _filler_impl[
    dtype: DType,
    layout: Layout,
    //,
    FuncType: def(Int) -> Scalar[dtype],
    *,
    use_runtime_layout: Bool = (
        not layout.all_dims_known() or layout.size() > BATCH_SIZE
    ),
](tensor: LayoutTensor[mut=True, dtype, layout, ...], filler: FuncType):
    """Fills a tensor with values generated by a filler function.

    This function iterates through the elements of the tensor and
    assigns values based on the provided filler function. It handles
    both compile-time and runtime layouts.

    Parameters:
        dtype: The data type of the tensor elements.
        layout: The layout of the tensor.
        FuncType: The filler function type.
        use_runtime_layout: Whether to use the runtime layout for filling.
            This parameter is defaulted to `True` if the layout is not
            statically known. If loop bounds are too large, it's better to
            use the runtime layout to avoid long compilation time.

    Args:
        tensor: The tensor to fill.
        filler: A function that takes an index and returns a scalar value.

    Performance:

        - For compile-time known layouts, the function uses parameter-time
          loop unrolling for optimal performance.
        - For runtime layouts, the function uses dynamic iteration.
        - Type casting is performed to ensure type compatibility.
    """

    comptime if not use_runtime_layout:
        comptime num_elements = tensor.layout.size() * tensor.element_size

        comptime for i in range(num_elements):
            var val = filler(i)
            tensor.ptr[i] = val.cast[tensor.dtype]()
    else:
        var num_elements = tensor.runtime_layout.size() * tensor.element_size
        for i in range(num_elements):
            var val = filler(i)
            tensor.ptr[i] = val.cast[tensor.dtype]()


def arange[
    dtype: DType,
    layout: Layout,
    /,
    *,
    use_runtime_layout: Bool = (
        not layout.all_dims_known() or layout.size() > BATCH_SIZE
    ),
](
    tensor: LayoutTensor[mut=True, dtype, layout, ...],
    start: Scalar[tensor.dtype] = 0,
    step: Scalar[tensor.dtype] = 1,
    end: Scalar[tensor.dtype] = max_finite[tensor.dtype](),
):
    """Fills a tensor with a sequence of values.

    This function generates a sequence of values within the specified range
    [start, end) with a given step, similar to `numpy.arange`, and fills
    the tensor with this sequence.

    Parameters:
        dtype: The data type of the tensor elements.
        layout: The layout of the tensor.
        use_runtime_layout: Whether to use the runtime layout for filling.
            This parameter is defaulted to `True` if the layout is not
            statically known. If loop bounds are too large, it's better to
            use the runtime layout to avoid long compilation time.

    Args:
        tensor: The tensor to fill.
        start: The starting value of the sequence.
        step: The step size between consecutive values.
        end: The ending value of the sequence (exclusive).

    Example:

        ```mojo
        from layout import Layout, LayoutTensor
        from layout._fillers import arange

        var storage = Array[Float32, 16](uninitialized=True)
        var tensor = LayoutTensor[.float32, Layout(4, 4)](storage)
        arange(tensor, 0, 0.5, 10)  # Fills with [0, 0.5, 1, 1.5, ...]
        ```
    """

    def filler(i: Int) {imm} -> Scalar[dtype]:
        return (Scalar[dtype](i) * step + start) % end

    # Use layout info for 2D tensors with simple (non-nested) shapes
    comptime if (
        len(tensor.layout) != 2
        or len(tensor.layout.shape[0]) != 1
        or len(tensor.layout.shape[1]) != 1
    ):
        _filler_impl[use_runtime_layout=use_runtime_layout](tensor, filler)
    else:
        var rows = Int(tensor.runtime_layout.shape[0][0])
        var cols = Int(tensor.runtime_layout.shape[1][0])
        for m, n in product(range(rows), range(cols)):
            tensor[m, n] = (Scalar[dtype](m * cols + n) * step + start) % end


def random[
    dtype: DType,
    layout: Layout,
    /,
    *,
    use_runtime_layout: Bool = (
        not layout.all_dims_known() or layout.size() > BATCH_SIZE
    ),
](
    tensor: LayoutTensor[mut=True, dtype, layout, ...],
    min: Scalar[tensor.dtype] = 0,
    max: Scalar[tensor.dtype] = 1,
):
    """Fills a tensor with random values.

    This function generates uniformly distributed random numbers within the
    specified range [min, max) and fills the tensor with these values.

    Parameters:
        dtype: The data type of the tensor elements.
        layout: The layout of the tensor.
        use_runtime_layout: Whether to use the runtime layout for filling.
            This parameter is defaulted to `True` if the layout is not
            statically known. If loop bounds are too large, it's better to
            use the runtime layout to avoid long compilation time.

    Args:
        tensor: The tensor to fill.
        min: The minimum value (inclusive).
        max: The maximum value (exclusive).

    Constraint:
        Not available on NVIDIA GPUs due to platform limitations.

    Example:

        ```mojo
        from layout import Layout, LayoutTensor
        from layout._fillers import random

        var storage = Array[Float32, 16](uninitialized=True)
        var tensor = LayoutTensor[.float32, Layout(4, 4)](storage)
        random(tensor, -1.0, 1.0)  # Fills with random values between -1 and 1
        ```
    """
    comptime assert not is_nvidia_gpu(), "Cannot run random on the gpu"

    def filler(i: Int) {imm} -> Scalar[dtype]:
        return random_float64(min.cast[.float64](), max.cast[.float64]()).cast[
            dtype
        ]()

    _filler_impl[use_runtime_layout=use_runtime_layout](tensor, filler)


def _filler_impl[
    dtype: DType,
    LayoutType: TensorLayout,
    //,
    FuncType: def(Int) -> Scalar[dtype],
    *,
    use_runtime_layout: Bool = (
        not LayoutType.all_dims_known
        or Coord[*LayoutType._shape_types].static_product > BATCH_SIZE
    ),
](tensor: TileTensor[mut=True, dtype, LayoutType, ...], filler: FuncType):
    """Fills a tensor with values generated by a filler function.

    This function iterates through the elements of the tensor and
    assigns values based on the provided filler function. It handles
    both compile-time and runtime layouts.

    Parameters:
        dtype: The data type of the tensor elements.
        LayoutType: The layout type of the tensor.
        FuncType: The filler function type.
        use_runtime_layout: Whether to use the runtime layout for filling.
            This parameter is defaulted to `True` if the layout is not
            statically known. If loop bounds are too large, it's better to
            use the runtime layout to avoid long compilation time.

    Args:
        tensor: The tensor to fill.
        filler: A function that takes an index and returns a scalar value.

    Performance:

        - For compile-time known layouts, the function uses parameter-time
          loop unrolling for optimal performance.
        - For runtime layouts, the function uses dynamic iteration.
        - Type casting is performed to ensure type compatibility.
    """

    comptime if not use_runtime_layout:
        comptime num_elements = type_of(
            tensor.layout.shape_coord()
        ).static_product * tensor.element_size

        comptime for i in range(num_elements):
            var val = filler(i)
            tensor.raw_store(i, val.cast[tensor.dtype]())
    else:
        var num_elements = tensor.layout.product() * tensor.element_size
        for i in range(num_elements):
            var val = filler(i)
            tensor.raw_store(i, val.cast[tensor.dtype]())


def arange[
    dtype: DType,
    LayoutType: TensorLayout,
    /,
    *,
    use_runtime_layout: Bool = (
        not LayoutType.all_dims_known
        or Coord[*LayoutType._shape_types].static_product > BATCH_SIZE
    ),
](
    tensor: TileTensor[mut=True, dtype, LayoutType, ...],
    start: Scalar[tensor.dtype] = 0,
    step: Scalar[tensor.dtype] = 1,
    end: Scalar[tensor.dtype] = max_finite[tensor.dtype](),
):
    """Fills a tensor with a sequence of values.

    This function generates a sequence of values within the specified range
    [start, end) with a given step, similar to `numpy.arange`, and fills
    the tensor with this sequence.

    Parameters:
        dtype: The data type of the tensor elements.
        LayoutType: The layout type of the tensor.
        use_runtime_layout: Whether to use the runtime layout for filling.
            This parameter is defaulted to `True` if the layout is not
            statically known. If loop bounds are too large, it's better to
            use the runtime layout to avoid long compilation time.

    Args:
        tensor: The tensor to fill.
        start: The starting value of the sequence.
        step: The step size between consecutive values.
        end: The ending value of the sequence (exclusive).

    Example:

        ```mojo
        from layout import Layout, LayoutTensor
        from layout._fillers import arange

        var storage = Array[Float32, 16](uninitialized=True)
        var tensor = LayoutTensor[.float32, Layout(4, 4)](storage)
        arange(tensor, 0, 0.5, 10)  # Fills with [0, 0.5, 1, 1.5, ...]
        ```
    """

    def filler(i: Int) {imm} -> Scalar[dtype]:
        return (Scalar[dtype](i) * step + start) % end

    # Use layout info for 2D tensors with simple (non-nested) shapes
    comptime if (
        tensor.flat_rank != 2
        or tensor.LayoutType._shape_types[0].__len__() != 1
        or tensor.LayoutType._shape_types[1].__len__() != 1
    ):
        _filler_impl[use_runtime_layout=use_runtime_layout](tensor, filler)
    else:
        # Provide evidence that flat_rank == 2 for the constraint system
        comptime assert tensor.flat_rank == 2
        var rows = Int(tensor.layout.shape[0]().value())
        var cols = Int(tensor.layout.shape[1]().value())
        for m, n in product(range(rows), range(cols)):
            tensor[m, n] = (Scalar[dtype](m * cols + n) * step + start) % end


def random[
    dtype: DType,
    LayoutType: TensorLayout,
    /,
    *,
    use_runtime_layout: Bool = (
        not LayoutType.all_dims_known
        or Coord[*LayoutType._shape_types].static_product > BATCH_SIZE
    ),
](
    tensor: TileTensor[mut=True, dtype, LayoutType, ...],
    min: Scalar[tensor.dtype] = 0,
    max: Scalar[tensor.dtype] = 1,
):
    """Fills a tensor with random values.

    This function generates uniformly distributed random numbers within the
    specified range [min, max) and fills the tensor with these values.

    Parameters:
        dtype: The data type of the tensor elements.
        LayoutType: The layout type of the tensor.
        use_runtime_layout: Whether to use the runtime layout for filling.
            This parameter is defaulted to `True` if the layout is not
            statically known. If loop bounds are too large, it's better to
            use the runtime layout to avoid long compilation time.

    Args:
        tensor: The tensor to fill.
        min: The minimum value (inclusive).
        max: The maximum value (exclusive).

    Constraint:
        Not available on NVIDIA GPUs due to platform limitations.

    Example:

        ```mojo
        from layout import Layout, LayoutTensor
        from layout._fillers import random

        var storage = Array[Float32, 16](uninitialized=True)
        var tensor = LayoutTensor[.float32, Layout(4, 4)](storage)
        random(tensor, -1.0, 1.0)  # Fills with random values between -1 and 1
        ```
    """
    comptime assert not is_nvidia_gpu(), "Cannot run random on the gpu"

    def filler(i: Int) {imm} -> Scalar[dtype]:
        return random_float64(min.cast[.float64](), max.cast[.float64]()).cast[
            dtype
        ]()

    _filler_impl[use_runtime_layout=use_runtime_layout](tensor, filler)
