# Whisper tests.

load(
    "//bazel:api.bzl",
    "modular_py_test",
    "requirement",
)

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "whisper",
    size = "large",
    srcs = glob(
        ["**/test_*.py"],
    ),
    tags = [
        "no-sandbox",
        "requires-network",
    ],
    target_compatible_with = select({
        "@platforms//os:macos": ["@platforms//:incompatible"],  # FIXME: MOCO-2411
        "//conditions:default": [],
    }),
    deps = [
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/engine",
        "//max/python/max/graph",
        "//max/python/max/pipelines/architectures/whisper",
        "//max/python/max/pipelines/lib",
        requirement("numpy"),
        requirement("torch"),
        requirement("transformers"),
        requirement("datasets"),
    ],
)
