load("//bazel:api.bzl", "lit_tests")

package(default_visibility = ["//visibility:private"])

_DATA = [
    "**/inputs/**/*.mojo",
    "**/test_package.foo",
    "**/test_std_mock/**",
    "**/test_std_mock_reexporter/**",
]

lit_tests(
    name = "mojo-parser",
    srcs = glob(
        [
            "**/*.mojo",
            "**/*.test",
        ],
        exclude = _DATA,
    ),
    data = ["//Mojo/test/test-packages"] + glob(_DATA),
    generate_litcfg = False,
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//Mojo/tools/kgen-opt",
        "//Mojo/tools/kgen-translate",
        # Used by some tests to precompile packages, so those tests exercise
        # the bytecode-loading paths.
        "//Mojo/tools/mojo",
    ],
)
