# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Speculative decoding utilities."""

from __future__ import annotations

from dataclasses import dataclass

__all__: list[str] = []


@dataclass
class _SpeculativeDecodingMetrics:
    """Metrics for speculative decoding."""

    num_speculative_tokens: int
    """The number of draft tokens the pipeline will speculate each time."""

    accepted_per_position: list[int] | None = None
    """Per-position acceptance counts.

    A list of length ``num_speculative_tokens`` where each element contains
    the count of draft tokens accepted at that position. Position 0 is the
    first draft token, position 1 is the second, etc.
    """

    num_verifications: int = 0
    """The number of verification rounds (batches) performed.

    Used to compute per-position acceptance rates and derived metrics.
    """

    def __post_init__(self) -> None:
        if self.accepted_per_position is None:
            self.accepted_per_position = [0] * self.num_speculative_tokens

    @property
    def draft_tokens_accepted(self) -> int:
        """The number of draft tokens accepted by the target model.

        Computed as the sum of per-position acceptance counts.
        """
        if self.accepted_per_position is None:
            return 0
        return sum(self.accepted_per_position)

    @property
    def draft_tokens_generated(self) -> int:
        """The number of draft tokens generated by the draft model.

        Computed as num_verifications * num_speculative_tokens.
        """
        return self.num_verifications * self.num_speculative_tokens

    @property
    def acceptance_rate(self) -> float:
        """Get the acceptance rate."""
        if self.draft_tokens_generated == 0:
            return 0.0
        return self.draft_tokens_accepted / self.draft_tokens_generated

    @property
    def avg_acceptance_length(self) -> float:
        """Get the average acceptance length."""
        if self.num_verifications == 0:
            return 0.0
        return self.draft_tokens_accepted / self.num_verifications

    @property
    def acceptance_rate_per_position(self) -> list[float]:
        """Get per-position acceptance rates.

        Returns a list of acceptance rates for each draft position. The rate
        at position i represents the probability that draft token i is accepted
        given that all previous draft tokens (0..i-1) were accepted. Empty when
        no verifications were performed: such a batch carries no acceptance
        information, and a row of zeros would dilute every consumer that
        averages these rates (e.g. the per-position histograms).
        """
        if self.num_verifications == 0 or self.accepted_per_position is None:
            return []
        return [
            count / self.num_verifications
            for count in self.accepted_per_position
        ]

    @property
    def output_tokens(self) -> int:
        """Total output tokens: accepted drafts + one bonus token per verification."""
        return self.draft_tokens_accepted + self.num_verifications
