load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//Mojo:consumers"])

modular_cc_binary(
    name = "mojo-repl-entry-point",
    srcs = glob(["*.cpp"]),
    # We need to prevent inline function expansion to guarantee our entry
    # point function is correctly invoked.
    copts = [
        "-O0",
        "-g0",
    ],
    internal_deps = select({
        # Under --config=hal-device-context we don't link the full DeviceContext,
        # but we need CompilationDevice and the HAL-only CompilerDeviceArch.
        "//:hal_device_context_enabled": [
            "//MLRT:Driver/CompilationDeviceImpl",
            "//MLRT:Driver/CompilerDeviceArch",
        ],
        "//conditions:default": [],
    }),
    linkopts = select({
        "@platforms//os:linux": [
            # Make sure this never gets stripped because it is used as a lldb breakpoint
            "-Wl,--export-dynamic-symbol=mojo_repl_main",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//Init",
        "//Mojo:CompilerRT",
        "//Mojo:MojoParser",
        "//Mojo:MojoTooling",
        "//Mojo:ObjectCompiler",
        "//Mojo:Pipeline",
        "//Mojo:ToolCommon",
        "//Support:Base",
        "//Support:Context",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:MlirLspServerLib",
    ],
)
