load("//bazel:api.bzl", "modular_py_binary", "modular_py_library", "pkg_files", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "benchmark_serving_lib",
    srcs = glob(
        ["*.py"],
        exclude = [
            "serve_replay.py",
        ],
    ),
    data = [
        ":benchmark_config_yaml_files",
    ],
    # Transformers secretly depends on jinja2
    ignore_extra_deps = [
        requirement("jinja2"),
        requirement("tiktoken"),
    ],
    deps = [
        "//max/python/max/benchmark/benchmark_shared",
        "//max/python/max/benchmark/benchmark_shared:model_csv",
        "//max/python/max/profiler",
        requirement("cyclopts"),
        requirement("jinja2"),
        requirement("numpy"),
        requirement("openai"),
        requirement("psutil"),
        requirement("pydantic"),
        requirement("pyyaml"),
        requirement("tiktoken"),
        requirement("transformers"),
        requirement("requests"),
    ],
)

modular_py_binary(
    name = "results_to_csv",
    srcs = ["results_to_csv.py"],
    main = "results_to_csv.py",
    deps = [
        "//max/python/max/benchmark/benchmark_shared:model_csv",
    ],
)

modular_py_binary(
    name = "serve_replay",
    srcs = ["serve_replay.py"],
    visibility = [":__subpackages__"],
    deps = [
        "//max/python/max/_entrypoints:pipelines",
        "//max/python/max/_entrypoints:replay_recording",
        requirement("click"),
        requirement("httpx"),
    ],
)

# TODO: This is maybe redundant since we already have yaml_files?
pkg_files(
    name = "benchmark_config_yaml_files",
    srcs = glob(["configs/*.yaml"]),
)
