load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "test_empty_batches",
    size = "large",
    srcs = ["test_text_generation_scheduler_empty_batches.py"],
    exec_properties = {
        "test.resources:gpu-memory": "23",
    },
    gpu_constraints = ["//:has_gpu"],
    tags = [
        "gpu",
        "manual",
        "no-pydeps",  # TODO: Fix and re-enable
        "no-sandbox",
        "requires-network",
    ],
    deps = [
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/modeling",
        "//max/python/max/serve",
        requirement("numpy"),
        requirement("pytest-asyncio"),
    ],
)
