load("//bazel:api.bzl", "modular_py_library", "requirement")

package(default_visibility = ["//max:consumers"])

modular_py_library(
    name = "engine",
    srcs = glob(["**/*.py"]),
    test_docstring_examples = True,
    deps = [
        "//max/python/max:_core",
        "//max/python/max/driver",
        "//max/python/max/graph",
        "//max/python/max/profiler",
        "@mojo//:python",
        requirement("numpy"),
    ],
)
