load("//bazel:api.bzl", "mojo_library")
load("//max/kernels/src:deprecations.bzl", "IGNORED_POINTER_DEPRECATIONS")

package(default_visibility = ["//max:consumers"])

mojo_library(
    name = "testdata",
    testonly = True,
    srcs = glob(["**/*.mojo"]),
    ignore_deprecated = IGNORED_POINTER_DEPRECATIONS,
    validate_missing_docs = False,
    deps = [
        "@mojo//:std",
    ],
)
