load("//bazel:api.bzl", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_test(
    name = "tests",
    srcs = glob(["*.py"]),
    env = {
        "MODULAR_ENABLE_PROFILING": "1",
    },
    deps = [
        "//max/python/max/profiler",
        requirement("pytest-asyncio"),
    ],
)
