load("//bazel:api.bzl", "lit_tests")

package(default_visibility = ["//visibility:private"])

_DATA = [
    "inputs/**",
    "internal/inputs/**",
]

filegroup(
    name = "fixtures",
    testonly = True,
    srcs = glob(
        [
            "inputs/**/*.ll",
            "inputs/**/*.mojo",
            "internal/inputs/**/*.ll",
            "internal/inputs/**/*.mojo",
        ],
        # `internal/inputs/` fixtures may not include every extension.
        allow_empty = True,
    ),
)

lit_tests(
    name = "test",
    srcs = glob(
        [
            "**/*.mlir",
            "**/*.mojo",
        ],
        exclude = _DATA,
    ),
    data = [":fixtures"],
    mojo_deps = [
        "//max:layout",
        "//max:max_mojo",
        "@mojo//:std",
    ],
    tags = ["gpu"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//Mojo/tools/kgen",
        "//Mojo/tools/kgen-opt",
        "//Mojo/tools/kgen-translate",
        "//Mojo/tools/llvm-module-split",
        "//Mojo/tools/mojo",
        "@llvm-project//llvm:llvm-as",
        "@llvm-project//llvm:llvm-dis",
        "@llvm-project//llvm:llvm-nm",
        "@llvm-project//llvm:llvm-objdump",
    ],
)

lit_tests(
    name = "test_std_srcs",
    # This tests require the std, where other tests do
    # not require them
    srcs = glob(["*.test"]),
    data = [
        ":fixtures",
        "@mojo//:std_srcs",
    ],
    env = {
        "MODULAR_MOJO_IMPORT_SRCS": "$(locations @mojo//:std_srcs)",
    },
    mojo_deps = [
        "@mojo//:std",
    ],
    tools = [
        "//Mojo/tools/hash-mlir",
        "//Mojo/tools/kgen",
        "//Mojo/tools/kgen-opt",
        "//Mojo/tools/kgen-translate",
    ],
)
