load("//bazel:api.bzl", "kgen_kernel", "modular_cc_test")

# gazelle:default_visibility //visibility:private

package(default_visibility = ["//visibility:private"])

exports_files(["lit-lldb-init.in"])

kgen_kernel(
    name = "test_kernels",
    testonly = True,
    src = "test_kernels.mlir",
)

modular_cc_test(
    name = "unittests",
    srcs = glob(["*.cpp"]),
    deps = [
        ":test_kernels",
        "//Mojo:MojoTooling",
    ],
)

modular_cc_test(
    name = "KGENDialectTest",
    srcs = glob(["kgen-dialect/*.cpp"]),
    deps = [
        "//Mojo:KGENDialect",
        "//Mojo:LITDialect",
        "//Mojo:ToolCommon",
    ],
)
