##===----------------------------------------------------------------------===##
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##===----------------------------------------------------------------------===##

name: Build and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "bazel/mojo.MODULE.bazel"

permissions:
  contents: read
  pull-requests: read

concurrency: # Only allow a single build/test run at a time for a PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["large-oss-linux"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Build and Test
        run: |
          if [[ -n "${BUILDBUDDY_TOKEN:-}" ]]; then
            # NOTE: Read+write token that only runs on trusted PRs.
            args=(
              --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_TOKEN
            )
          else
            # NOTE: Readonly token that we're ok with being here.
            args=(
              --remote_header=x-buildbuddy-api-key=gJPttl2LQEONgD2aKziQ
              --remote_upload_local_results=false
            )
          fi

          # Print CPU info for debugging purposes
          lscpu || true

          # NOTE: Skip the buildbuddy sidecar on linux where the machine is too small.
          # TODO: Remove this once upstream has fixed the issue.
          export BB_DISABLE_SIDECAR=1

          ./bazelw test --config=ci \
            --config=public-cache \
            "${args[@]}" \
            --build_tag_filters=-skip-external-ci,-requires-network \
            --test_tag_filters=-skip-external-ci,-requires-network \
            --config=prebuilt-mojo \
            -- \
            //... \
            -//AsyncRT/... \
            -//Cache/... \
            -//Config/... \
            -//Init/... \
            -//Mojo/... \
            -//Support/... \
            //Mojo/docs/site/... \
            //Mojo/examples/... \
            //Mojo/integration-test/... \
            //Mojo/python/... \
            //Mojo/stdlib/...
        env:
          BUILDBUDDY_TOKEN: ${{ secrets.BUILDBUDDY_TOKEN }}
